### ISSUE TITLE
flop count not found for t4 with precision

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-gpt#237]
I get a key error from the SpeedMonitor on a T4 machine (running pretrain/openwebtext.py with default settings).

```
Traceback (most recent call last):
  File "/project/studios/this_studio/lit-gpt/pretrain/openwebtext.py", line 271, in <module>
    CLI(setup)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/project/studios/this_studio/lit-gpt/pretrain/openwebtext.py", line 80, in setup
    fabric.launch(main, resume=resume)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 788, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 870, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 875, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/project/studios/this_studio/lit-gpt/pretrain/openwebtext.py", line 84, in main
    speed_monitor = SpeedMonitor(fabric, window_size=50, time_unit="seconds")
  File "/project/studios/this_studio/lit-gpt/lit_gpt/speed_monitor.py", line 173, in __init__
    self.flops_available = get_flops_available(fabric.device, fabric._connector._precision_input)
  File "/project/studios/this_studio/lit-gpt/lit_gpt/speed_monitor.py", line 99, in get_flops_available
    raise KeyError(
KeyError: 'flop count not found for t4 with precision: bf16-mixed; MFU cannot be calculated and reported.'
```
In my case, I'm not interested in the speed. So I have to uncomment/delete the code in many places which I found inconvenient.

Proposals:

A) Make it a warning instead.
B)  Provide an easy way to disable it via `SpeedMonitor(enabled=False)`
C) Make it a callback so we can easily remove it from the callback list without changing the rest of the code
D) ?

**Comment by carmocca** [comment]
T4 doesnt support bf16 precision, this causes the error. Changing the precision will avoid the error. We could check `is_bf16_supported` before configuring the precision

**Comment by awaelchli** [comment]
I overlooked the bf16 setting, sorry!
