### ISSUE TITLE
Can lit-gpt provide a simple example that runs on Colab Pro+?

### ISSUE THREAD

**Issue by Keiku** [Lightning-AI/lit-gpt#254]
When I ran `notebooks/falcon-inference.ipynb` on Colab Pro+, I got an error when installing PyTorch. Is it possible to change it to run lit-gpt a little easier in a common environment like Colab Pro+?

**Comment by carmocca** [comment]
What error did you get? Do you have any ideas on how we could make that easier?

**Comment by Keiku** [comment]
I'm using A100 GPU as runtime for Colab Pro+. This is the result of copying the notebook and running it as follows. I think the problem is probably the version of PyTorch. I think it is easy to use if it works with past stable versions such as 1.12.0 and 2.0.0, but is there any reason why it must be 2.1.0dev?

```python
# clone Lit-GPT
!git clone https://github.com/Lightning-AI/lit-gpt
%cd lit-gpt/
```

```
Cloning into 'lit-gpt'...
remote: Enumerating objects: 2469, done.
remote: Counting objects: 100% (1180/1180), done.
remote: Compressing objects: 100% (507/507), done.
remote: Total 2469 (delta 940), reused 753 (delta 669), pack-reused 1289
Receiving objects: 100% (2469/2469), 797.02 KiB | 1.82 MiB/s, done.
Resolving deltas: 100% (1625/1625), done.
/content/lit-gpt
```

```python
# for CUDA
!pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch>=2.1.0dev' -q

# install the dependencies
!pip install huggingface_hub -r requirements.txt -q
```

```
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 GB 889.0 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.5/93.5 MB 19.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.12 requires torch<2.1,>=1.7, but you have torch 2.1.0.dev20230711+cu118 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.1.0.dev20230711+cu118 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.0.dev20230711+cu118 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 2.1.0.dev20230711+cu118 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 2.1.0.dev20230711+cu118 which is incompatible.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 22.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 106.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.0/198.0 kB 26.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 MB 16.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.2/486.2 kB 46.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 105.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.7/596.7 kB 55.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.9/68.9 kB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 728.8/728.8 kB 69.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 722.4/722.4 kB 55.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.6/581.6 kB 54.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 16.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 26.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.7 MB/s eta 0:00:00
  Building wheel for lightning (pyproject.toml) ... done
```
```python
# download the weights
!python scripts/download.py --repo_id tiiuae/falcon-7b
!python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/tiiuae/falcon-7b
```
```
Downloading (…)l-00001-of-00002.bin: 100% 9.95G/9.95G [00:39<00:00, 252MB/s]
Fetching 5 files: 100% 5/5 [00:39<00:00,  7.97s/it]
Traceback (most recent call last):
  File "/content/lit-gpt/scripts/convert_hf_checkpoint.py", line 15, in <module>
    from lit_gpt import Config
  File "/content/lit-gpt/lit_gpt/__init__.py", line 1, in <module>
    from lit_gpt.model import GPT, build_rope_cache, apply_rope
  File "/content/lit-gpt/lit_gpt/model.py", line 13, in <module>
    from lit_gpt.config import Config
  File "/content/lit-gpt/lit_gpt/config.py", line 9, in <module>
    from lit_gpt.utils import find_multiple
  File "/content/lit-gpt/lit_gpt/utils.py", line 15, in <module>
    from lightning.fabric.loggers import CSVLogger
  File "/usr/local/lib/python3.10/dist-packages/lightning/__init__.py", line 28, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/__init__.py", line 26, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 24, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/callback.py", line 22, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/pit.py", line 23, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 48, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/usr/local/lib/python3.10/dist-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 845, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIlEESB_SB_l
```
```python
# run inference
!python generate/base.py \
        --prompt "Hello, my name is" \
        --checkpoint_dir checkpoints/tiiuae/falcon-7b \
        --quantize llm.int8
```
```
Traceback (most recent call last):
  File "/content/lit-gpt/generate/base.py", line 9, in <module>
    import lightning as L
  File "/usr/local/lib/python3.10/dist-packages/lightning/__init__.py", line 28, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/__init__.py", line 26, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 24, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/callback.py", line 22, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/audio/pit.py", line 23, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py", line 48, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/usr/local/lib/python3.10/dist-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 845, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIlEESB_SB_l
```

**Comment by rohanrdy** [comment]
Same issue. On looking further it seems like the problem is with the torch 2.1.0 (nightly version) which is supposedly required for converting the weights to lit-gpt format; is not supported by some other libraries. This also means that we cannot finetune the falcon 7b parameter on google collab untill we find a workaround.

Screenshot for reference:

![image](https://github.com/Lightning-AI/lit-gpt/assets/89927943/65392426-f070-4dcd-b80c-912e2c69febc)

**Comment by carmocca** [comment]
We use some attention features that are only present in torch 2.1

You should be able to unblock yourselves by uninstalling these libraries which lit-gpt doesn't use

`pip uninstall -y torchaudio torchdata torchtext torchvision`

**Comment by louisoutin** [comment]
I just tried on colab pro+ and it seems torchaudio etc are preinstalled there. I had the same error but @carmocca answers fixes the issue.
Thanks

**Comment by rohanrdy** [comment]
> We use some attention features that are only present in torch 2.1
> 
> You should be able to unblock yourselves by uninstalling these libraries which lit-gpt doesn't use
> 
> `pip uninstall -y torchaudio torchdata torchtext torchvision`

That did the trick. Thank you Carlos!

**Comment by Keiku** [comment]
@carmocca Thank you for letting me know in the comments. When I ran it, I got the following result. I also got an error with `--quantize llm.int8` but it worked after removing that option.

```python
# clone Lit-GPT
!git clone https://github.com/Lightning-AI/lit-gpt
%cd lit-gpt/
```
```
Cloning into 'lit-gpt'...
remote: Enumerating objects: 2483, done.
remote: Counting objects: 100% (1194/1194), done.
remote: Compressing objects: 100% (525/525), done.
remote: Total 2483 (delta 946), reused 752 (delta 665), pack-reused 1289
Receiving objects: 100% (2483/2483), 812.75 KiB | 25.40 MiB/s, done.
Resolving deltas: 100% (1631/1631), done.
/content/lit-gpt
```
```python

# It was already uninstalled for this runtime because I ran it a few times.
!pip uninstall -y fastai torchaudio torchdata torchtext torchvision

# for CUDA
!pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch>=2.1.0dev' -q

# install the dependencies
!pip install huggingface_hub -r requirements.txt -q
```
```
WARNING: Skipping fastai as it is not installed.
WARNING: Skipping torchaudio as it is not installed.
WARNING: Skipping torchdata as it is not installed.
WARNING: Skipping torchtext as it is not installed.
WARNING: Skipping torchvision as it is not installed.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
```
```python
# download the weights
!python scripts/download.py --repo_id tiiuae/falcon-7b
!python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/tiiuae/falcon-7b
```
```
Downloading (…)l-00001-of-00002.bin:  86% 8.56G/9.95G [00:36<00:03, 438MB/s]

Downloading (…)l-00001-of-00002.bin:  87% 8.61G/9.95G [00:36<00:03, 431MB/s]

Downloading (…)l-00001-of-00002.bin:  87% 8.66G/9.95G [00:36<00:02, 432MB/s]

Downloading (…)l-00001-of-00002.bin:  88% 8.71G/9.95G [00:36<00:02, 436MB/s]

Downloading (…)l-00001-of-00002.bin:  88% 8.77G/9.95G [00:36<00:02, 429MB/s]

Downloading (…)l-00001-of-00002.bin:  89% 8.82G/9.95G [00:36<00:02, 432MB/s]

Downloading (…)l-00001-of-00002.bin:  89% 8.87G/9.95G [00:36<00:02, 423MB/s]

Downloading (…)l-00001-of-00002.bin:  90% 8.92G/9.95G [00:36<00:02, 440MB/s]

Downloading (…)l-00001-of-00002.bin:  90% 8.98G/9.95G [00:37<00:02, 441MB/s]

Downloading (…)l-00001-of-00002.bin:  91% 9.03G/9.95G [00:37<00:02, 449MB/s]

Downloading (…)l-00001-of-00002.bin:  91% 9.08G/9.95G [00:37<00:01, 455MB/s]

Downloading (…)l-00001-of-00002.bin:  92% 9.13G/9.95G [00:37<00:01, 464MB/s]

Downloading (…)l-00001-of-00002.bin:  92% 9.19G/9.95G [00:37<00:01, 464MB/s]

Downloading (…)l-00001-of-00002.bin:  93% 9.24G/9.95G [00:37<00:01, 469MB/s]

Downloading (…)l-00001-of-00002.bin:  93% 9.29G/9.95G [00:37<00:01, 472MB/s]

Downloading (…)l-00001-of-00002.bin:  94% 9.34G/9.95G [00:37<00:01, 462MB/s]

Downloading (…)l-00001-of-00002.bin:  94% 9.40G/9.95G [00:37<00:01, 467MB/s]

Downloading (…)l-00001-of-00002.bin:  95% 9.45G/9.95G [00:38<00:01, 464MB/s]

Downloading (…)l-00001-of-00002.bin:  95% 9.50G/9.95G [00:38<00:00, 466MB/s]

Downloading (…)l-00001-of-00002.bin:  96% 9.55G/9.95G [00:38<00:00, 466MB/s]

Downloading (…)l-00001-of-00002.bin:  97% 9.60G/9.95G [00:38<00:00, 466MB/s]

Downloading (…)l-00001-of-00002.bin:  97% 9.66G/9.95G [00:38<00:01, 271MB/s]

Downloading (…)l-00001-of-00002.bin:  97% 9.70G/9.95G [00:39<00:01, 220MB/s]

Downloading (…)l-00001-of-00002.bin:  98% 9.75G/9.95G [00:39<00:00, 269MB/s]

Downloading (…)l-00001-of-00002.bin:  99% 9.80G/9.95G [00:39<00:00, 316MB/s]

Downloading (…)l-00001-of-00002.bin:  99% 9.86G/9.95G [00:39<00:00, 360MB/s]

Downloading (…)l-00001-of-00002.bin: 100% 9.95G/9.95G [00:39<00:00, 252MB/s]
Fetching 5 files: 100% 5/5 [00:39<00:00,  7.96s/it]
Model config {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1}
Processing checkpoints/tiiuae/falcon-7b/pytorch_model-00001-of-00002.bin
Processing checkpoints/tiiuae/falcon-7b/pytorch_model-00002-of-00002.bin
```
```python
# run inference
!python generate/base.py \
        --prompt "Hello, my name is" \
        --checkpoint_dir checkpoints/tiiuae/falcon-7b \
        --quantize llm.int8
```
```
usage: base.py
       [-h]
       [--config CONFIG]
       [--print_config[=flags]]
       [--prompt PROMPT]
       [--num_samples NUM_SAMPLES]
       [--max_new_tokens MAX_NEW_TOKENS]
       [--top_k TOP_K]
       [--temperature TEMPERATURE]
       [--checkpoint_dir CHECKPOINT_DIR]
       [--quantize QUANTIZE]
       [--strategy STRATEGY]
       [--devices DEVICES]
       [--precision PRECISION]
base.py: error: Parser key "quantize":
  Does not validate against any of the Union subtypes
  Subtypes: (typing.Literal['bnb.nf4', 'bnb.nf4-dq', 'bnb.fp4', 'bnb.fp4-dq', 'bnb.int8', 'gptq.int4'], <class 'NoneType'>)
  Errors:
    - Expected a typing.Literal['bnb.nf4', 'bnb.nf4-dq', 'bnb.fp4', 'bnb.fp4-dq', 'bnb.int8', 'gptq.int4']
    - Expected a <class 'NoneType'>
  Given value type: <class 'str'>
  Given value: llm.int8
```
```python
# run inference
!python generate/base.py \
        --prompt "Hello, my name is" \
        --checkpoint_dir checkpoints/tiiuae/falcon-7b # \
        # --quantize llm.int8
```
```
Loading model 'checkpoints/tiiuae/falcon-7b/lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1}
Time to instantiate model: 0.13 seconds.
Time to load the model weights: 11.27 seconds.
Global seed set to 1234
Hello, my name is Jack.
Some people think that dogs are like people. They see them as loyal, loving, and caring friends. I don't believe that these traits apply to dogs.
I've never seen a dog at a funeral or read a
Time for inference 1: 1.57 sec total, 31.83 tokens/sec
Memory used: 14.50 GB
```

**Comment by rohanrdy** [comment]
There has been a new commit yesterday d16f924db91bac43d04ebb91a0a2eb7219af37d9

Using `--quantize bnb.int8` should work.

![image](https://github.com/Lightning-AI/lit-gpt/assets/89927943/bf4df4fc-9a18-4a50-984e-dd93a8bedba5)
