### ISSUE TITLE
Fine-tuning error for Falcon-7B & RedPajama-INCITE-Base-3B --> "ValueError: max() arg is an empty sequence"

### ISSUE THREAD

**Issue by rohanrdy** [Lightning-AI/lit-gpt#260]
Hi, I am trying to finetune RedPajama-INCITE-Base-3B-v1 on a custom small alpaca format dataset size of 170. When I execute the finetuning with both `adapter_v2.py` ( and even `lora.py`), I get the same error of `max_seq_length = max(lengths)  ValueError: max() arg is an empty sequence`.
I tried poking around in both of the python files to rectify the ValueError but to no avail. Even changing `override_max_seq_length = None` to force a maximum sequence length didn't work.

I got the same error when I was trying to finetune the Falcon-7b model.

Please help me proceed further. Thank you.

---

Google collab logs:

```python
# Preparing dataset
!python scripts/prepare_alpaca.py \
    --destination_path data/alpaca \
    --checkpoint_dir checkpoints/togethercomputer/RedPajama-INCITE-Base-3B-v1
```
```
Loading data file...
Loading tokenizer...
train has 0 samples
test has 172 samples
Processing train split ...
0it [00:00, ?it/s]
Processing test split ...
100% 172/172 [00:00<00:00, 1402.62it/s]
```
The main part:
```python
# Finetuning the model
!python finetune/adapter_v2.py \
    --data_dir data/alpaca \
    --checkpoint_dir checkpoints/togethercomputer/RedPajama-INCITE-Base-3B-v1 \
    --out_dir out/adapter/alpaca \
    --precision 16-true
```
```
/content/lit-gpt/finetune/adapter_v2.py:303: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

  from jsonargparse.cli import CLI
{'eval_interval': 600, 'save_interval': 1000, 'eval_iters': 100, 'log_interval': 1, 'devices': 1, 'learning_rate': 0.003, 'batch_size': 128.0, 'micro_batch_size': 2, 'gradient_accumulation_iters': 64.0, 'epoch_size': 50000, 'num_epochs': 5, 'max_iters': 125000, 'weight_decay': 0.02, 'warmup_steps': 781.0}
Global seed set to 1337
Loading model 'checkpoints/togethercomputer/RedPajama-INCITE-Base-3B-v1/lit_model.pth' with {'org': 'togethercomputer', 'name': 'RedPajama-INCITE-Base-3B-v1', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 256, 'padded_vocab_size': 50432, 'n_layer': 32, 'n_head': 32, 'n_embd': 2560, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': True, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 10240, 'condense_ratio': 1, 'adapter_prompt_length': 10, 'adapter_start_layer': 2}
Number of trainable parameters: 2677184
Number of non trainable parameters: 2775531520
/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py:881: PossibleUserWarning: The model passed to `Fabric.setup()` has parameters on different devices. Since `move_to_device=True`, all parameters will be moved to the new device. If this is not desired, set  `Fabric.setup(..., move_to_device=False)`.
  rank_zero_warn(
Traceback (most recent call last):
  File "/content/lit-gpt/finetune/adapter_v2.py", line 305, in <module>
    CLI(setup)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/content/lit-gpt/finetune/adapter_v2.py", line 82, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 789, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 871, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 876, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/content/lit-gpt/finetune/adapter_v2.py", line 121, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/content/lit-gpt/finetune/adapter_v2.py", line 140, in train
    max_seq_length, longest_seq_length, longest_seq_ix = get_max_seq_length(train_data)
  File "/content/lit-gpt/finetune/adapter_v2.py", line 283, in get_max_seq_length
    max_seq_length = max(lengths)
ValueError: max() arg is an empty sequence
```

**Comment by carmocca** [comment]
You would get this error if your data is empty. Did you check the contents of your train data?

**Comment by rohanrdy** [comment]
Yes, I have checked the contents and it is exactly similar to the alpaca format. Here is an excerpt of it:

```json
[
    {
        "instruction": "Explain data abstraction.",
        "input": "",
        "output": "Data abstraction is a technique used in computer programming to separate the implementation details of a data type from its interface, allowing the implementation to be changed without affecting the code that uses it. This is often achieved through the use of abstract data types (ADTs), which are defined by the operations they support rather than their specific implementation, or through the use of interfaces and classes in object-oriented programming languages. Data abstraction helps to reduce the complexity of software systems by allowing code to be written in a modular and flexible way and by hiding the underlying details of data types from the user."
    },
    {
        "instruction": "What is a syntax error",
        "input": "",
        "output": "A syntax error is an error in the structure of a programming language's code. It occurs when the code does not conform to the rules of the programming language's syntax. Syntax errors can occur for a variety of reasons, such as using the wrong punctuation, omitting required elements, or using an incorrect keyword. Syntax errors are usually detected by a compiler or interpreter when the code is being compiled or executed, and they can prevent the code from running correctly. To fix a syntax error, the code must be revised to conform to the correct syntax of the programming language."
    }
]
```

Do you think there is an error in my data or in my `prepare_alpaca.py`? Or in my understanding of finetuning with `adapter_v2.py`?
I cannot figure it out. Thank you.

**Comment by carmocca** [comment]
If you open a terminal and do `data = torch.load("data/alpaca/train.pt")`, it should appear as an empty list. This suggests a problem when `prepare_alpaca.py` is run. In fact, it did say

```python
Processing train split ...
0it [00:00, ?it/s]
```

Note the 0 iterations.

You should try debugging if this is doing what you expect: https://github.com/Lightning-AI/lit-gpt/blob/main/scripts/prepare_alpaca.py#L58-L60

**Comment by rohanrdy** [comment]
Thank you so much Carlos! You have explained in great detail and pointed me in the right direction. I cannot overstate how timely you were. Things like this show how debugging is very an important skill.

The issue was with the `test_split_size` value, which by default is 2000 whereas my custom dataset's total size is 172 haha.

**Comment by carmocca** [comment]
Glad I could help! I'll reopen this because we should totally add a check to avoid this. Would you like to contribute it?

**Comment by patrickhwood** [comment]
Hmmm.  test_split_size should probably be a fraction of the total training set size, and the CLI parameter changed to siomething like test_percentage.  I can play around with this.

**Comment by patrickhwood** [comment]
See PR https://github.com/Lightning-AI/lit-gpt/pull/264

**Comment by rohanrdy** [comment]
Setting the test split size as a percentage is wise! And here I was trying to raise an exception instead of solving it for the user. Nice PR.
