### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling cublasGemmStridedBatchedExFix

### ISSUE THREAD

**Issue by bkowshik** [Lightning-AI/lit-gpt#266]
Got this error after entering the second prompt during inference and interactive mode.

```
>> Reply: Traceback (most recent call last):
  File "/home/user/code/lit-gpt/chat/base.py", line 286, in <module>
    CLI(main)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/user/code/lit-gpt/chat/base.py", line 192, in main
    tokens_generated = decode(fabric, tokenizer, y)
  File "/home/user/code/lit-gpt/chat/base.py", line 109, in decode
    for token in token_stream:
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/user/code/lit-gpt/chat/base.py", line 61, in generate
    logits = model(idx.view(1, -1), max_seq_length, input_pos)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 116, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/code/lit-gpt/lit_gpt/model.py", line 104, in forward
    x, self.kv_caches[i] = block(x, (cos, sin), max_seq_length, mask, input_pos, self.kv_caches[i])
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/code/lit-gpt/lit_gpt/model.py", line 167, in forward
    h, new_kv_cache = self.attn(n_1, rope, max_seq_length, mask, input_pos, kv_cache)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/code/lit-gpt/lit_gpt/model.py", line 247, in forward
    y = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedExFix(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

**Comment by carmocca** [comment]
Interesting, I had the same error happen to me with H100s, using `TransformerEngine`: https://github.com/NVIDIA/TransformerEngine/issues/295

If you can reliably reproduce this and can share your precise setup, I'm sure somebody like @eqy might be interested in debugging this further.

**Comment by eqy** [comment]
It would be helpful to get a minimal repro script for this. I suspect that unless simply calling the module `torch.nn.functional.scaled_dot_product_attention` on its own with the same shape yields the same error, the error is actually happening in a previous layer as was the case in the linked `TransformerEngine` issue.
