### ISSUE TITLE
FSDP Training crashes everytime, while single GPU training works fine.

### ISSUE THREAD

**Issue by ashutosh-dwivedi-e3502** [Lightning-AI/lit-gpt#303]
I am fine-tuning the falcon-7B model on AWS `g512x.large` instance with the `adapter_v2` script. This works when I keep the device=1 as in the original script, but when I increase the device count to 4, training fails with the following error : 

```
/databricks/driver/lit-gpt/finetune/adapter_v2.py:302: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

  from jsonargparse.cli import CLI
/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/pydantic/_migration.py:282: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
/databricks/driver/lit-gpt/finetune/adapter_v2.py:302: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

  from jsonargparse.cli import CLI
/databricks/driver/lit-gpt/finetune/adapter_v2.py:302: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

  from jsonargparse.cli import CLI
/databricks/driver/lit-gpt/finetune/adapter_v2.py:302: JsonargparseDeprecationWarning: 
    Only use the public API as described in https://jsonargparse.readthedocs.io/en/stable/#api-reference.
    Importing from jsonargparse.cli is kept only to avoid breaking code that does not correctly use the public
    API. It will no longer be available from v5.0.0.

  from jsonargparse.cli import CLI
/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/pydantic/_migration.py:282: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/pydantic/_migration.py:282: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/pydantic/_migration.py:282: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

[rank: 2] Global seed set to 1337
[rank: 1] Global seed set to 1337
[rank: 3] Global seed set to 1337
[rank: 0] Global seed set to 1337
[rank: 3] Global seed set to 1340
[rank: 2] Global seed set to 1339
[rank: 1] Global seed set to 1338
[rank: 0] Global seed set to 1337
Traceback (most recent call last):
  File "/databricks/driver/lit-gpt/finetune/adapter_v2.py", line 304, in <module>
    CLI(setup)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/databricks/driver/lit-gpt/finetune/adapter_v2.py", line 79, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 805, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 887, in _wrap_and_launch
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 892, in _wrap_with_setup
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/driver/lit-gpt/finetune/adapter_v2.py", line 120, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/databricks/driver/lit-gpt/finetune/adapter_v2.py", line 180, in train
    fabric.backward(loss / gradient_accumulation_iters)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 398, in backward
    self._strategy.backward(tensor, module, *args, **kwargs)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/strategies/strategy.py", line 179, in backward
    self.precision.backward(tensor, module, *args, **kwargs)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/plugins/precision/fsdp.py", line 136, in backward
    super().backward(tensor, model, *args, **kwargs)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/lightning/fabric/plugins/precision/precision.py", line 91, in backward
    tensor.backward(*args, **kwargs)
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/lit-gpt/lib/python3.11/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB. GPU 1 has a total capacty of 22.20 GiB of which 203.12 MiB is free. Process 9841 has 22.00 GiB memory in use. Of the allocated memory 19.13 GiB is allocated by PyTorch, and 1.69 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[E ProcessGroupNCCL.cpp:456] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=8743, OpType=_ALLGATHER_BASE, NumelIn=51794866, NumelOut=207179464, Timeout(ms)=1800000) ran for 1800070 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=8743, OpType=_ALLGATHER_BASE, NumelIn=51794866, NumelOut=207179464, Timeout(ms)=1800000) ran for 1800976 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:470] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:476] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:838] [Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=8743, OpType=_ALLGATHER_BASE, NumelIn=51794866, NumelOut=207179464, Timeout(ms)=1800000) ran for 1800070 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=8743, OpType=_ALLGATHER_BASE, NumelIn=51794866, NumelOut=207179464, Timeout(ms)=1800000) ran for 1800070 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:470] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:476] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:838] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=8743, OpType=_ALLGATHER_BASE, NumelIn=51794866, NumelOut=207179464, Timeout(ms)=1800000) ran for 1800976 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=8743, OpType=_ALLGATHER_BASE, NumelIn=51794866, NumelOut=207179464, Timeout(ms)=1800000) ran for 1800976 milliseconds before timing out.```

**Comment by ashutosh-dwivedi-e3502** [comment]
The same training fails on a p3.16xlarge instance (supports NVME). , with  16-true precision also.

**Comment by ashutosh-dwivedi-e3502** [comment]
fails with adapter v1 and `cpu_offloading=True` as well.

**Comment by KOVVURISATYANARAYANAREDDY** [comment]
Hey how much GPU memory is required to train Falcon-7B on alpaca dataset. When i tried with 1 40gb GPU A100, i am getting OOM. Any Suggestions? Thank you.

**Comment by Colonelvinnie** [comment]
I would also like to add that sharding seems to cause a CUDA out of memory issue much earlier than not using any at all, utilising adapter.py

The following error outputs are done with micro_batch_size = 1 and precision set as "bf16-true", and the system has a number of GTX3090 24GB GPUs available. The environment variable related to "max_split_size_mb" is set to 128.

With 1 GPU, the following occurs:
```
iter 3436 step 53: loss 2.9911, iter time: 400.10ms
Traceback (most recent call last):
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.06 GiB. GPU 0 has a total capacty of 23.70 GiB of which 1.27 GiB is free. Including non-PyTorch memory, this process has 22.43 GiB memory in use. Of the allocated memory 12.62 GiB is allocated by PyTorch, and 8.65 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

With 2 GPUs:
```
iter 4 step 0: loss 2.6297, iter time: 827.80ms
...
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.06 GiB. GPU 1 has a total capacty of 23.70 GiB of which 1.60 GiB is free. Including non-PyTorch memory, this process has 22.10 GiB memory in use. Of the allocated memory 12.16 GiB is allocated by PyTorch, and 8.76 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
...
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.06 GiB. GPU 0 has a total capacty of 23.70 GiB of which 2.15 GiB is free. Including non-PyTorch memory, this process has 21.54 GiB memory in use. Of the allocated memory 12.16 GiB is allocated by PyTorch, and 8.20 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

With 4:
```
iter 28 step 1: loss 3.1707, iter time: 1705.49ms
...
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.06 GiB. GPU 1 has a total capacty of 23.70 GiB of which 3.42 GiB is free. Including non-PyTorch memory, this process has 20.28 GiB memory in use. Of the allocated memory 10.47 GiB is allocated by PyTorch, and 8.63 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[rank: 1] Child process with PID 433976 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
Killed
```

And with 6:
```
iter 180 step 18: loss 2.7013, iter time: 3271.34ms
...
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.06 GiB. GPU 4 has a total capacty of 23.70 GiB of which 4.29 GiB is free. Including non-PyTorch memory, this process has 19.41 GiB memory in use. Of the allocated memory 8.74 GiB is allocated by PyTorch, and 9.48 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[rank: 4] Child process with PID 456677 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
Killed
```

From what I observe, using more than 1 GPU instead caused a CUDA out of memory issue to occur earlier while causing iteration times to be much longer. In addition, for some reason the size reserved by PyTorch but unallocated is larger than the size tried to be allocated.

**Comment by Davegdd** [comment]
Also getting that strange behaviour @Colonelvinnie mentioned with finetune/lora.py, 7b model fits and trains in single RTX 3090 but fails with OOM when setting devices=2 (2xRTX 3090) or devices=3 (1xRTX 3090 and 2xRTX 3080). If I understand correctly FSDP splits the model between several GPUs so if it fits in 1 3090 it should fit in 2 right?
