### ISSUE TITLE
Issues regarding convert_lit_checkpoint

### ISSUE THREAD

**Issue by wxl-lxw** [Lightning-AI/lit-gpt#318]
Hello! I noticed that you uploaded a new script at scripts/convert_lit_checkpoint.py, and I'm attempting to run it. I have already used Adapter technique to finetune the falcon-7b model and put my `lit_model_adapter_finetuned.pth` file in `checkpoints/tiiuae/falcon-7b`. However, when I execute the command
 `python scripts/convert_lit_checkpoint.py
 --checkpoint_dir=checkpoints/tiiuae/falcon-7b 
--checkpoint_name=lit_model_adapter_finetuned` just following your guidance, 
I encounter an error stating `convert_lit_checkpoint.py: error: Unrecognized arguments: --checkpoint_name`

Could you please advise on how to resolve this issue?

Thank you very much.

**Comment by JustinGoheen** [comment]
Hi @wxl-lxw! Can you please tell me if your `scripts/convert_lit_checkpoint.py` file shows the following in `convert_lit_checkpoint`:

```python
def convert_lit_checkpoint(
    *,
    checkpoint_name: str,
    checkpoint_dir: Path = Path("checkpoints/tiiuae/falcon-7b"),
    model_name: Optional[str] = None,
) -> None:
```

If it doesn't, can you please update your clone of Lit-GPT.

**Comment by wxl-lxw** [comment]
Yes, it is. and I noted that someone also reported this issue in [#313 ](url) **Question 1**.

**Comment by JustinGoheen** [comment]
I'll be submitting a PR with a fix ... In the interim, here is the snippet you'll need.

```python
@torch.inference_mode()
def convert_lit_checkpoint(
    *,
    checkpoint_name: str = None,
    checkpoint_dir: Path = Path("checkpoints/tiiuae/falcon-7b"),
    model_name: Optional[str] = None,
) -> None:
    if model_name is None:
        model_name = checkpoint_dir.name
    config = Config.from_name(model_name)

    if "falcon" in model_name:
        copy_fn = partial(copy_weights_falcon, "40b" if config.n_embd == 8192 else "7b")
    elif config._mlp_class == "LLaMAMLP":
        raise NotImplementedError(f"Conversion for {model_name} is not yet supported")
    else:
        copy_fn = copy_weights_gpt_neox

    # initialize a new empty state dict to hold our new weights
    sd = {}

    # checkpoint_name cannot be hardcoded because there exists different outputs such as
    # ("lit_model_finetuned.pth", "lit_model_lora_finetuned.pth", "lit_model_adapter_finetuned.pth"")
    pth_file = checkpoint_dir / "".join([checkpoint_name, ".pth"])
    bin_file = "".join([checkpoint_name, ".bin"])

    with incremental_save(checkpoint_dir / bin_file) as saver:
        with contextlib.ExitStack() as stack:
            lit_weights = stack.enter_context(lazy_load(pth_file))
            copy_fn(sd, lit_weights, saver=saver)
            gc.collect()
        saver.save(sd)
```

and run the following in terminal, please:

```sh
python scripts/convert_lit_checkpoint.py \
    --checkpoint_name lit_model_finetuned \
    --checkpoint_dir checkpoints/tiiuae/falcon-7b
```

**Comment by wxl-lxw** [comment]
Thanks a lot! But when I was trying to convert `stablelm-base-alpha-3b`, it occurs that:
```python scripts/convert_lit_checkpoint.py --checkpoint_name lit_model_adapter_finetuned --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b
/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/pydantic/_migration.py:282: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Traceback (most recent call last):
  File "/home/wang6201/lit-gpt_old/scripts/convert_lit_checkpoint.py", line 139, in <module>
    CLI(convert_lit_checkpoint)
  File "/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang6201/lit-gpt_old/scripts/convert_lit_checkpoint.py", line 132, in convert_lit_checkpoint
    copy_fn(sd, lit_weights, saver=saver)
  File "/home/wang6201/lit-gpt_old/scripts/convert_lit_checkpoint.py", line 96, in copy_weights_gpt_neox
    to_name = weight_map[name]
              ~~~~~~~~~~^^^^^^
KeyError: 'model'
```

Could you please advise on how to resolve this issue?

Thank you very much.

**Comment by JustinGoheen** [comment]
I've been working on adding support for various models and haven't made it to stablelm yet.

**Comment by JustinGoheen** [comment]
@carmocca should we open a single issue to track conversion for the model groups?

**Comment by carmocca** [comment]
StableLM is gpt-neox based. The issue arises from converting a checkpoint trained by fabric, where the structure is

```{model: ordinary_state_dict}```

We should unwrap that dict if the "model" key is present

**Comment by monk1337** [comment]
I was trying to run the code in colab and getting issue, So I changed the command from this

`!python finetune/lora.py --checkpoint_dir checkpoints/microsoft/phi-2/ --precision bf16-true
`
to

`!python finetune/lora.py --io.checkpoint_dir checkpoints/microsoft/phi-2/ --precision bf16-true
`
and it worked.
