### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by wxl-lxw** [Lightning-AI/lit-gpt#324]
Hello! I saw you updated `scripts/convert_lit_checkpoint.py` just now, but when I was executing 
```
python scripts/convert_lit_checkpoint.py \
    --checkpoint_name lit_model_adapter_finetuned.pth \
    --checkpoint_dir checkpoints/tiiuae/falcon-7b
```
it still raised an error that:
```
/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/pydantic/_migration.py:282: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Traceback (most recent call last):
  File "/home/wang6201/lit-gpt/scripts/convert_lit_checkpoint.py", line 140, in <module>
    CLI(convert_lit_checkpoint, as_positional=False)
  File "/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/home/wang6201/anaconda3/envs/lit-gpt/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang6201/lit-gpt/scripts/convert_lit_checkpoint.py", line 132, in convert_lit_checkpoint
    copy_fn(sd, lit_weights, saver=saver)
  File "/home/wang6201/lit-gpt/scripts/convert_lit_checkpoint.py", line 60, in copy_weights_falcon
    to_name = weight_map[name]
              ~~~~~~~~~~^^^^^^
KeyError: 'model'
```
Could you please advise on how to resolve this issue?

Thank you very much.

**Comment by JustinGoheen** [comment]
this is being addressed in #322

**Comment by JustinGoheen** [comment]
did you by any chance move a StableLM model into the checkpoint directory?

**Comment by wxl-lxw** [comment]
No. I just follow your tutorial:
```
pip install huggingface_hub

python scripts/download.py --repo_id tiiuae/falcon-7b

python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/tiiuae/falcon-7b
```
then finetuning with adapter:
```python finetune/adapter.py --checkpoint_dir checkpoints/tiiuae/falcon-7b
```` 

then put the generated `lit_model_finetuned.pth` into `checkpoints/tiiuae/falcon-7b`, then execute:
```
python scripts/convert_lit_checkpoint.py \
    --checkpoint_name lit_model_finetuned.pth \
    --checkpoint_dir checkpoints/tiiuae/falcon-7b
```
and raised the error mentioned above.

**Comment by JustinGoheen** [comment]
addressing this is https://github.com/Lightning-AI/lit-gpt/pull/341
