### ISSUE TITLE
Dimension error with Falcon-7B and LoRA

### ISSUE THREAD

**Issue by samvoisiniml** [Lightning-AI/lit-gpt#348]
Hello,

I am encountering an error when trying to finetune Falcon-7B on two Nvidia Titan V GPUs. I am giving this command:

```bash
python finetune/lora.py --checkpoint_dir checkpoints/tiiuae/falcon-7b-instruct/ --data_dir data/alpaca/ --precision 16-mixed
```

and I receive the following error:

```
RuntimeError: Given groups=3, expected weight to be divisible by 3 at dimension 0, but got weight of size [[4672, 2, 1]] instead
```

I have modified a few parameters in `finetune/lora.py` in order to avoid OOM errors.

```python
eval_interval = 100
save_interval = 100
eval_iters = 100
log_interval = 1
devices = 2  # MODIFIED 1 -> 2
# change this value to force a maximum sequence length
override_max_seq_length = None

# Hyperparameters
learning_rate = 3e-4
batch_size = 1  # MODIFIED 128 -> 1
micro_batch_size = 1  # MODIFIED 4 -> 1
gradient_accumulation_iters = batch_size // micro_batch_size
assert gradient_accumulation_iters > 0
max_iters = 50000  # train dataset size
weight_decay = 0.01
lora_r = 2  # MODIFIED 8 -> 2
lora_alpha = 16
lora_dropout = 0.05
lora_query = True
lora_key = True  # MODIFIED False -> True
lora_value = True
lora_projection = False
lora_mlp = False
lora_head = False
warmup_steps = 100
...
```

The error seems to only appear after setting `lora_key=True` . As I understand it, this should apply a low rank approximation to the keys weight matrix for each attention head. Is this understanding correct and if so, does anyone know why this error is occuring?

Thank you for your time!

PS - here is the full out put including stack trace:

```
python finetune/lora.py --checkpoint_dir checkpoints/tiiuae/falcon-7b-instruct/ --data_dir data/alpaca/ --precision 16-mixed
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

{'eval_interval': 100, 'save_interval': 100, 'eval_iters': 100, 'log_interval': 1, 'devices': 2, 'learning_rate': 0.0003, 'batch_size': 1, 'micro_batch_size': 1, 'gradient_accumulation_iters': 1, 'max_iters': 50000, 'weight_decay': 0.01, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.05, 'lora_query': True, 'lora_key': True, 'lora_value': True, 'lora_projection': False, 'lora_mlp': False, 'lora_head': False, 'warmup_steps': 100}
[rank: 1] Global seed set to 1337
[rank: 0] Global seed set to 1337
Loading model 'checkpoints/tiiuae/falcon-7b-instruct/lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b-instruct', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1, 'r': 2, 'alpha': 16, 'dropout': 0.05, 'to_query': True, 'to_key': True, 'to_value': True, 'to_projection': False, 'to_mlp': False, 'to_head': False}
Number of trainable parameters: 1,171,456
Number of non trainable parameters: 7,217,189,760
[rank: 1] Global seed set to 1338
[rank: 0] Global seed set to 1337
Validating ...
Traceback (most recent call last):
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/finetune/lora.py", line 319, in <module>
    CLI(setup)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/finetune/lora.py", line 81, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 806, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 888, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 893, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/finetune/lora.py", line 135, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/finetune/lora.py", line 156, in train
    validate(fabric, model, val_data, tokenizer, longest_seq_length)  # sanity check
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/finetune/lora.py", line 241, in validate
    logits = model(input_ids)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
Traceback (most recent call last):
  File "finetune/lora.py", line 319, in <module>
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    CLI(setup)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "finetune/lora.py", line 81, in setup
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/wrappers.py", line 116, in forward
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 806, in launch
    output = self._forward_module(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 887, in _wrap_and_launch
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return launcher.launch(to_run, *args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 893, in _wrap_with_setup
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 821, in forward
    return to_run(*args, **kwargs)
  File "finetune/lora.py", line 135, in main
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "finetune/lora.py", line 156, in train
    validate(fabric, model, val_data, tokenizer, longest_seq_length)  # sanity check
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "finetune/lora.py", line 241, in validate
    logits = model(input_ids)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/lora.py", line 516, in forward
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    x, *_ = block(x, (cos, sin), max_seq_length)
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/lightning/fabric/wrappers.py", line 116, in forward
    output = self._forward_module(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 821, in forward
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 821, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 164, in forward
    return self.checkpoint_fn(  # type: ignore[misc]
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/_compile.py", line 24, in inner
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/lora.py", line 516, in forward
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 457, in checkpoint
    x, *_ = block(x, (cos, sin), max_seq_length)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    ret = function(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 821, in forward
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/model.py", line 168, in forward
    h, new_kv_cache = self.attn(n_1, rope, max_seq_length, mask, input_pos, kv_cache)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/model.py", line 205, in forward
    qkv = self.attn(x)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 164, in forward
    return self.checkpoint_fn(  # type: ignore[misc]
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 321, in _fn
    return fn(*args, **kwargs)
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return fn(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 457, in checkpoint
    ret = function(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/lora.py", line 369, in forward
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    after_B = F.conv1d(
RuntimeError: Given groups=3, expected weight to be divisible by 3 at dimension 0, but got weight of size [[4672, 2, 1]] instead
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/model.py", line 168, in forward
    h, new_kv_cache = self.attn(n_1, rope, max_seq_length, mask, input_pos, kv_cache)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/model.py", line 205, in forward
    qkv = self.attn(x)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/home/sam.voisin/healthcare-data-suite/lit-gpt/lit_gpt/lora.py", line 369, in forward
    after_B = F.conv1d(
RuntimeError: Given groups=3, expected weight to be divisible by 3 at dimension 0, but got weight of size [[4672, 2, 1]] instead
```

**Comment by Andrei-Aksionov** [comment]
Hello @samvoisiniml 
Thanks for a such rich description of the issue.
Just to clarify: this issue happens only on two GPUs or on a single too?

**Comment by samvoisin** [comment]
Hi @Andrei-Aksionov 

This is only happening when I use two GPUs, but I'm not sure if that is the cause because I run out of memory when only using one.

Sorry! That is probably not very helpful for identifying the cause.

**Comment by Andrei-Aksionov** [comment]
I am asking because I access only to a single GPU :)
I've just checked on a single T4 with `16-true` precision and the same parameters as you used and can confirm the same exact issue. 
I am in the middle of working on another issue so as soon as I finish - will try to fix this one.

**Comment by reeceshuttle** [comment]
@Andrei-Aksionov @samvoisin I have gotten this exact same bug as well, running on a single NVIDIA A100 GPU.
