### ISSUE TITLE
Finetuning creates additional keys that must be handled in convert_lit_checkpoint

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lit-gpt#355]
See https://github.com/Lightning-AI/lit-gpt/issues/347#issuecomment-1664182016.

Finetuning creates additional key `.attn.gating_factor` at a minimum. Need to identify and handle all new keys created by finetuning.

**Comment by solablue** [comment]
Used #350 Still same. Thank you always!

```
Traceback (most recent call last):
  File "/content/lit-gpt/scripts/convert_lit_checkpoint.py", line 237, in <module>
    CLI(convert_lit_checkpoint, as_positional=False)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/lit-gpt/scripts/convert_lit_checkpoint.py", line 229, in convert_lit_checkpoint
    copy_fn(sd, lit_weights, saver=saver)
  File "/content/lit-gpt/scripts/convert_lit_checkpoint.py", line 135, in copy_weights_llama
    to_name = weight_map[from_name]
KeyError: 'transformer.h.{}.attn.gating_factor'

```

**Comment by JustinGoheen** [comment]
finetuning with adapter_v2 raises KeyError for `lm_head.adapter_bias`

**Comment by MrJungle1** [comment]
@JustinGoheen , Hello, I also encountered the same problem. In order to try quickly, I used lora finetune to create a 1b model pythia-1b, and finally generated lit_model_lora_finetuned.pth, but when I used convert_lit_checkpoint.py to try to convert the lit_gpt format to the original format, I encountered to the following error.
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/01d4019a-8af5-43ce-bbec-43368a3e517d)

**Comment by JustinGoheen** [comment]
I can add a check for a key then, and raise an appropriate error. I’ll also update the tutorial with a note about this.

**Comment by MrJungle1** [comment]
@awaelchli  Hello, I also encountered the same problem, I used lora finetune to llama2-7b, and finally generated lit_model_lora_finetuned.pth, but when I used convert_lit_checkpoint.py to try to convert the lit_gpt format to the original format, I encountered to the same error follow.
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/f872b9ff-0c45-4236-810a-1dc01bebdb3f)

**Comment by MrJungle1** [comment]
@solablue Did you solve this problem? I need to convert the pth after lora finetune to the original hf format.

**Comment by MrJungle1** [comment]
@awaelchli @carmocca @JustinGoheen But in my opinion, many people may need this function. If I want to transfer my finetune model to Hugging Face, I need hf format. So I think it is necessary to support this feature.

**Comment by JustinGoheen** [comment]
@MrJungle1 I opened #374 to address your issue with LoRA

**Comment by solablue** [comment]
@MrJungle1 Not yet. I am still waiting for the update for this issue.

**Comment by JustinGoheen** [comment]
a new model must be created. as mentioned here -> https://github.com/Lightning-AI/lit-gpt/issues/183#issuecomment-1618843317 and here -> https://github.com/Lightning-AI/lit-gpt/issues/183#issuecomment-1619103370

**Comment by carmocca** [comment]
As described, this cannot be supported until there's HF models with adapter weights. #397 added a nicer error message for this
