### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'themes'

### ISSUE THREAD

**Issue by NonaryR** [Lightning-AI/lit-gpt#376]
I'm just curios, why I need gradio to prepare dataset? =)
This is my lightning dependency

`lightning = {git = "https://github.com/Lightning-AI/lightning", rev = "master", extras = ["extra"]}`

```
python scripts/prepare_alpaca.py 


Traceback (most recent call last):
  File "/workspaces/llama/lit-gpt/scripts/prepare_alpaca.py", line 15, in <module>
    from lit_gpt.tokenizer import Tokenizer
  File "/workspaces/llama/lit-gpt/lit_gpt/__init__.py", line 1, in <module>
    from lit_gpt.model import GPT
  File "/workspaces/llama/lit-gpt/lit_gpt/model.py", line 14, in <module>
    from lit_gpt.config import Config
  File "/workspaces/llama/lit-gpt/lit_gpt/config.py", line 8, in <module>
    from lit_gpt.utils import find_multiple
  File "/workspaces/llama/lit-gpt/lit_gpt/utils.py", line 15, in <module>
    from lightning.fabric.loggers import CSVLogger
  File "/home/r.gilaztdinov.ext/.cache/pypoetry/virtualenvs/talkllama-Y9RISVDk-py3.10/lib/python3.10/site-packages/lightning/__init__.py", line 18, in <module>
    from lightning.app import storage  # noqa: E402
  File "/home/r.gilaztdinov.ext/.cache/pypoetry/virtualenvs/talkllama-Y9RISVDk-py3.10/lib/python3.10/site-packages/lightning/app/__init__.py", line 24, in <module>
    from lightning.app import components  # noqa: E402, F401
  File "/home/r.gilaztdinov.ext/.cache/pypoetry/virtualenvs/talkllama-Y9RISVDk-py3.10/lib/python3.10/site-packages/lightning/app/components/__init__.py", line 11, in <module>
    from lightning.app.components.serve.auto_scaler import AutoScaler
  File "/home/r.gilaztdinov.ext/.cache/pypoetry/virtualenvs/talkllama-Y9RISVDk-py3.10/lib/python3.10/site-packages/lightning/app/components/serve/__init__.py", line 3, in <module>
    from lightning.app.components.serve.gradio_server import ServeGradio
  File "/home/r.gilaztdinov.ext/.cache/pypoetry/virtualenvs/talkllama-Y9RISVDk-py3.10/lib/python3.10/site-packages/lightning/app/components/serve/gradio_server.py", line 35, in <module>
    class ServeGradio(LightningWork, abc.ABC):
  File "/home/r.gilaztdinov.ext/.cache/pypoetry/virtualenvs/talkllama-Y9RISVDk-py3.10/lib/python3.10/site-packages/lightning/app/components/serve/gradio_server.py", line 58, in ServeGradio
    def __init__(self, *args: Any, theme: Optional[gradio.themes.Base] = None, **kwargs: Any):
AttributeError: module 'gradio' has no attribute 'themes'
```

**Comment by JustinGoheen** [comment]
can you please share your lightning version

**Comment by NonaryR** [comment]
```
pip list | grep light
lightning                 2.1.0.dev0
lightning-api-access      0.0.5
lightning-cloud           0.5.37
lightning-fabric          2.0.6
lightning-utilities       0.9.0
pytorch-lightning         2.0.6
```

**Comment by JustinGoheen** [comment]
did you create a new venv or conda env for this? you should only see the following when filtering for "light"

```
lightning                2.1.0.dev0
lightning-cloud          0.5.37
lightning-utilities      0.8.0
pytorch-lightning        2.0.5
```

also, I wonder if poetry is causing a version conflict somehow ... since you clearly have the correct version listed in pip

**Comment by NonaryR** [comment]
I don't install something else. Just this https://github.com/Lightning-AI/lightning

And I have problem with gradio for preparing dataset?

**Comment by JustinGoheen** [comment]
you should create a new poetry environment for Lit-GPT so that when you install using the instructions in the README, your dependency versions match. The version differences are shown below:

```
pip list | grep light
lightning                 2.1.0.dev0  # correct version
lightning-api-access      0.0.5  # not needed
lightning-cloud           0.5.37  # correct version
lightning-fabric          2.0.6  # included in lightning, no need for a stand alone install
lightning-utilities       0.9.0 # should be 0.8.0
pytorch-lightning         2.0.6 # should be 2.0.5
```

**Comment by JustinGoheen** [comment]
@NonaryR can you please let me know if the issue has been resolved

**Comment by NonaryR** [comment]
I'm not checked it, because I will not use this repo. So, you can close it, or whatever.
