### ISSUE TITLE
Cuda out of Memory Run time Error

### ISSUE THREAD

**Issue by jeetendraabvv** [Lightning-AI/lit-gpt#399]
Following Error encountering while finetuning falcon-7 using adavter_v2.
We have 01 A40 GPU of 48GB 
.

{'eval_interval': 600, 'save_interval': 1000, 'eval_iters': 100, 'log_interval': 1, 'devices': 1, 'learning_rate': 0.003, 'batch_size': 128.0, 'micro_batch_size': 2, 'gradient_accumulation_iters': 64.0, 'epoch_size': 50000, 'num_epochs': 5, 'max_iters': 125000, 'weight_decay': 0.02, 'warmup_steps': 781.0}
Loading model 'checkpoints\\tiiuae\\falcon-7b\\lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1, 'adapter_prompt_length': 10, 'adapter_start_layer': 2}
Number of trainable parameters: 3,839,186
Number of non trainable parameters: 7,216,889,856
Validating ...
Recommend a movie for me to watch during the weekend and explain the reason.
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Recommend a movie for me to watch during the weekend and explain the reason.

#### ![img](img/3.jpg)

> I think you should watch "The Martian". This movie is very interesting, because you can imagine yourself in the hero's place.

#### ![img](img/4.jpg)

> I think you should watch "The Martian". This movie is very interesting, because you can image yourself in the hero's place.

#### ![img](img/5.jpg)

> I think
Estimated TFLOPs: 192.04
Measured TFLOPs: 184.84
C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\pydantic\_migration.py:283: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Using bfloat16 Automatic Mixed Precision (AMP)
Global seed set to 1337
C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\lightning\fabric\fabric.py:930: PossibleUserWarning: The model passed to `Fabric.setup()` has parameters on different devices. Since `move_to_device=True`, all parameters will be moved to the new device. If this is not desired, set  `Fabric.setup(..., move_to_device=False)`.
  rank_zero_warn(
Global seed set to 1337
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\lit-gpt-main\finetune\adapter_v2.py", line 303, in <module>
    CLI(setup)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\jsonargparse\_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\jsonargparse\_cli.py", line 147, in _run_component
    return component(**cfg)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\finetune\adapter_v2.py", line 80, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\lightning\fabric\fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\lightning\fabric\fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\lightning\fabric\fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\finetune\adapter_v2.py", line 119, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\finetune\adapter_v2.py", line 175, in train
    logits = model(input_ids, max_seq_length=max_seq_length, lm_head_chunk_size=128)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\lightning\fabric\wrappers.py", line 117, in forward
    output = self._forward_module(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\lit_gpt\adapter.py", line 98, in forward
    x, *_ = block(x, (cos, sin), max_seq_length)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\lit_gpt\adapter.py", line 149, in forward
    x = x + h + self.mlp(n_2)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\lit_gpt\model.py", line 277, in forward
    x = self.fc(x)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\lit_test\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\lit-gpt-main\lit_gpt\adapter_v2.py", line 35, in adapter_v2_new_forward
    return self.adapter_scale * (torch.nn.functional.linear(input, self.weight, self.bias) + self.adapter_bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 76.00 MiB. GPU 0 has a total capacty of 44.72 GiB of which 16.94 MiB is free. Of the allocated memory 42.96 GiB is allocated by PyTorch, and 714.50 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by aniketmaurya** [comment]
hi @jeetendraabvv, try tweaking the `micro_batch_size` and `precision` as `bf16-true`. [This tutorial](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/oom.md) talks about all the settings you can tweak to avoid OOM error.

**Comment by jeetendraabvv** [comment]
@aniketmaurya  Thank You.
Is there any way to display the progress or processing of the running finetuning command like Expected Time of Execution etc.

**Comment by carmocca** [comment]
The repo doesn't implement that at the moment
