### ISSUE TITLE
generate/lora.py encounter RuntimeError

### ISSUE THREAD

**Issue by ian00000** [Lightning-AI/lit-gpt#425]
I successfully finetune Falcon-7b using lora, but I encountered a RuntimeError when generating text using my model.

Here's the Error message:

```python
/usr/local/lib/python3.10/dist-packages/pydantic/_migration.py:283: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Loading model 'checkpoints/tiiuae/falcon-7b/lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1, 'r': 8, 'alpha': 16, 'dropout': 0.05, 'to_query': True, 'to_key': False, 'to_value': True, 'to_projection': False, 'to_mlp': False, 'to_head': False}
Traceback (most recent call last):
  File "/content/lit-gpt/generate/lora.py", line 158, in <module>
    CLI(main)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/content/lit-gpt/generate/lora.py", line 106, in main
    model = GPT(config)
  File "/content/lit-gpt/lit_gpt/lora.py", line 471, in __init__
    h=nn.ModuleList(Block(config) for _ in range(config.n_layer)),
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 279, in __init__
    self += modules
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 320, in __iadd__
    return self.extend(modules)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 401, in extend
    for i, module in enumerate(modules):
  File "/content/lit-gpt/lit_gpt/lora.py", line 471, in <genexpr>
    h=nn.ModuleList(Block(config) for _ in range(config.n_layer)),
  File "/content/lit-gpt/lit_gpt/lora.py", line 552, in __init__
    self.attn = CausalSelfAttention(config)
  File "/content/lit-gpt/lit_gpt/lora.py", line 573, in __init__
    self.attn = LoRAQKVLinear(
  File "/content/lit-gpt/lit_gpt/lora.py", line 207, in __init__
    self.lora_A = nn.Parameter(self.linear.weight.new_zeros((r * sum(enable_lora), in_features)))  # (4, 128)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parameter.py", line 39, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```

Thanks for your help!

**Comment by carmocca** [comment]
What command did you run precisely?

**Comment by ian00000** [comment]
I ran

!python generate/lora.py \
        --prompt "請問貓的羅馬拼音是什麼" \
        --checkpoint_dir checkpoints/tiiuae/falcon-7b \
        --quantize bnb.int8 \
        --max_new_tokens 500

**Comment by carmocca** [comment]
I found the cause of this issue. This pops up when the model is quantized on initialization, where the `LoRALinear.linear.weight` is already of `uint8` dtype. The lora A and B need to be created with its own dtype

#596 will fix it
