### ISSUE TITLE
generate/lora.py run with error

### ISSUE THREAD

**Issue by Never-up** [Lightning-AI/lit-gpt#431]
### my environment  is gpu of v100 with 32G
when run 
```bash
python finetune/lora.py --checkpoint_dir ./stablelm-base-alpha-3b/ --precision "32-true"
is funished successful . 
```
but when run with error
```bash
 python generate/lora.py --prompt "Recommend a movie to watch on the weekend." --precision "32-true" --checkpoint_dir ./stablelm-base-alpha-3b/
```
i don`t know why problem of argument？
error As follows：
```bash
Traceback (most recent call last):
  File "/mnt/workspace/lit-gpt/generate/lora.py", line 158, in <module>
    CLI(main)
  File "/home/pai/lib/python3.9/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/pai/lib/python3.9/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/mnt/workspace/lit-gpt/generate/lora.py", line 112, in main
    model.load_state_dict(checkpoint, strict=quantize is None)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GPT:
        Missing key(s) in state_dict: "lm_head.linear.weight", "transformer.h.0.attn.attn.linear.weight", "transformer.h.0.attn.attn.linear.bias", "transformer.h.0.attn.proj.linear.weight", "transformer.h.0.attn.proj.linear.bias", "transformer.h.0.mlp.fc.linear.weight", "transformer.h.0.mlp.fc.linear.bias", "transformer.h.0.mlp.proj.linear.weight", "transformer.h.0.mlp.proj.linear.bias", "transformer.h.1.attn.attn.linear.weight", "transformer.h.1.attn.attn.linear.bias", "transformer.h.1.attn.proj.linear.weight", "transformer.h.1.attn.proj.linear.bias", "transformer.h.1.mlp.fc.linear.weight", "transformer.h.1.mlp.fc.linear.bias", "transformer.h.1.mlp.proj.linear.weight", "transformer.h.1.mlp.proj.linear.bias", "transformer.h.2.attn.attn.linear.weight", "transformer.h.2.attn.attn.linear.bias", "transformer.h.2.attn.proj.linear.weight", "transformer.h.2.attn.proj.linear.bias", "transformer.h.2.mlp.fc.linear.weight", "transformer.h.2.mlp.fc.linear.bias", "transformer.h.2.mlp.proj.linear.weight", "transformer.h.2.mlp.proj.linear.bias", "transformer.h.3.attn.attn.linear.weight", "transformer.h.3.attn.attn.linear.bias", "transformer.h.3.attn.proj.linear.weight", "transformer.h.3.attn.proj.linear.bias", "transformer.h.3.mlp.fc.linear.weight", "transformer.h.3.mlp.fc.linear.bias", "transformer.h.3.mlp.proj.linear.weight", "transformer.h.3.mlp.proj.linear.bias", "transformer.h.4.attn.attn.linear.weight", "transformer.h.4.attn.attn.linear.bias", "transformer.h.4.attn.proj.linear.weight", "transformer.h.4.attn.proj.linear.bias", "transformer.h.4.mlp.fc.linear.weight", "transformer.h.4.mlp.fc.linear.bias", "transformer.h.4.mlp.proj.linear.weight", "transformer.h.4.mlp.proj.linear.bias", "transformer.h.5.attn.attn.linear.weight", "transformer.h.5.attn.attn.linear.bias", "transformer.h.5.attn.proj.linear.weight", "transformer.h.5.attn.proj.linear.bias", "transformer.h.5.mlp.fc.linear.weight", "transformer.h.5.mlp.fc.linear.bias", "transformer.h.5.mlp.proj.linear.weight", "transformer.h.5.mlp.proj.linear.bias", "transformer.h.6.attn.attn.linear.weight", "transformer.h.6.attn.attn.linear.bias", "transformer.h.6.attn.proj.linear.weight", "transformer.h.6.attn.proj.linear.bias", "transformer.h.6.mlp.fc.linear.weight", "transformer.h.6.mlp.fc.linear.bias", "transformer.h.6.mlp.proj.linear.weight", "transformer.h.6.mlp.proj.linear.bias", "transformer.h.7.attn.attn.linear.weight", "transformer.h.7.attn.attn.linear.bias", "transformer.h.7.attn.proj.linear.weight", "transformer.h.7.attn.proj.linear.bias", "transformer.h.7.mlp.fc.linear.weight", "transformer.h.7.mlp.fc.linear.bias", "transformer.h.7.mlp.proj.linear.weight", "transformer.h.7.mlp.proj.linear.bias", "transformer.h.8.attn.attn.linear.weight", "transformer.h.8.attn.attn.linear.bias", "transformer.h.8.attn.proj.linear.weight", "transformer.h.8.attn.proj.linear.bias", "transformer.h.8.mlp.fc.linear.weight", "transformer.h.8.mlp.fc.linear.bias", "transformer.h.8.mlp.proj.linear.weight", "transformer.h.8.mlp.proj.linear.bias", "transformer.h.9.attn.attn.linear.weight", "transformer.h.9.attn.attn.linear.bias", "transformer.h.9.attn.proj.linear.weight", "transformer.h.9.attn.proj.linear.bias", "transformer.h.9.mlp.fc.linear.weight", "transformer.h.9.mlp.fc.linear.bias", "transformer.h.9.mlp.proj.linear.weight", "transformer.h.9.mlp.proj.linear.bias", "transformer.h.10.attn.attn.linear.weight", "transformer.h.10.attn.attn.linear.bias", "transformer.h.10.attn.proj.linear.weight", "transformer.h.10.attn.proj.linear.bias", "transformer.h.10.mlp.fc.linear.weight", "transformer.h.10.mlp.fc.linear.bias", "transformer.h.10.mlp.proj.linear.weight", "transformer.h.10.mlp.proj.linear.bias", "transformer.h.11.attn.attn.linear.weight", "transformer.h.11.attn.attn.linear.bias", "transformer.h.11.attn.proj.linear.weight", "transformer.h.11.attn.proj.linear.bias", "transformer.h.11.mlp.fc.linear.weight", "transformer.h.11.mlp.fc.linear.bias", "transformer.h.11.mlp.proj.linear.weight", "transformer.h.11.mlp.proj.linear.bias", "transformer.h.12.attn.attn.linear.weight", "transformer.h.12.attn.attn.linear.bias", "transformer.h.12.attn.proj.linear.weight", "transformer.h.12.attn.proj.linear.bias", "transformer.h.12.mlp.fc.linear.weight", "transformer.h.12.mlp.fc.linear.bias", "transformer.h.12.mlp.proj.linear.weight", "transformer.h.12.mlp.proj.linear.bias", "transformer.h.13.attn.attn.linear.weight", "transformer.h.13.attn.attn.linear.bias", "transformer.h.13.attn.proj.linear.weight", "transformer.h.13.attn.proj.linear.bias", "transformer.h.13.mlp.fc.linear.weight", "transformer.h.13.mlp.fc.linear.bias", "transformer.h.13.mlp.proj.linear.weight", "transformer.h.13.mlp.proj.linear.bias", "transformer.h.14.attn.attn.linear.weight", "transformer.h.14.attn.attn.linear.bias", "transformer.h.14.attn.proj.linear.weight", "transformer.h.14.attn.proj.linear.bias", "transformer.h.14.mlp.fc.linear.weight", "transformer.h.14.mlp.fc.linear.bias", "transformer.h.14.mlp.proj.linear.weight", "transformer.h.14.mlp.proj.linear.bias", "transformer.h.15.attn.attn.linear.weight", "transformer.h.15.attn.attn.linear.bias", "transformer.h.15.attn.proj.linear.weight", "transformer.h.15.attn.proj.linear.bias", "transformer.h.15.mlp.fc.linear.weight", "transformer.h.15.mlp.fc.linear.bias", "transformer.h.15.mlp.proj.linear.weight", "transformer.h.15.mlp.proj.linear.bias". 
        Unexpected key(s) in state_dict: "lm_head.weight", "transformer.h.0.attn.attn.weight", "transformer.h.0.attn.attn.bias", "transformer.h.0.attn.proj.weight", "transformer.h.0.attn.proj.bias", "transformer.h.0.mlp.fc.weight", "transformer.h.0.mlp.fc.bias", "transformer.h.0.mlp.proj.weight", "transformer.h.0.mlp.proj.bias", "transformer.h.1.attn.attn.weight", "transformer.h.1.attn.attn.bias", "transformer.h.1.attn.proj.weight", "transformer.h.1.attn.proj.bias", "transformer.h.1.mlp.fc.weight", "transformer.h.1.mlp.fc.bias", "transformer.h.1.mlp.proj.weight", "transformer.h.1.mlp.proj.bias", "transformer.h.2.attn.attn.weight", "transformer.h.2.attn.attn.bias", "transformer.h.2.attn.proj.weight", "transformer.h.2.attn.proj.bias", "transformer.h.2.mlp.fc.weight", "transformer.h.2.mlp.fc.bias", "transformer.h.2.mlp.proj.weight", "transformer.h.2.mlp.proj.bias", "transformer.h.3.attn.attn.weight", "transformer.h.3.attn.attn.bias", "transformer.h.3.attn.proj.weight", "transformer.h.3.attn.proj.bias", "transformer.h.3.mlp.fc.weight", "transformer.h.3.mlp.fc.bias", "transformer.h.3.mlp.proj.weight", "transformer.h.3.mlp.proj.bias", "transformer.h.4.attn.attn.weight", "transformer.h.4.attn.attn.bias", "transformer.h.4.attn.proj.weight", "transformer.h.4.attn.proj.bias", "transformer.h.4.mlp.fc.weight", "transformer.h.4.mlp.fc.bias", "transformer.h.4.mlp.proj.weight", "transformer.h.4.mlp.proj.bias", "transformer.h.5.attn.attn.weight", "transformer.h.5.attn.attn.bias", "transformer.h.5.attn.proj.weight", "transformer.h.5.attn.proj.bias", "transformer.h.5.mlp.fc.weight", "transformer.h.5.mlp.fc.bias", "transformer.h.5.mlp.proj.weight", "transformer.h.5.mlp.proj.bias", "transformer.h.6.attn.attn.weight", "transformer.h.6.attn.attn.bias", "transformer.h.6.attn.proj.weight", "transformer.h.6.attn.proj.bias", "transformer.h.6.mlp.fc.weight", "transformer.h.6.mlp.fc.bias", "transformer.h.6.mlp.proj.weight", "transformer.h.6.mlp.proj.bias", "transformer.h.7.attn.attn.weight", "transformer.h.7.attn.attn.bias", "transformer.h.7.attn.proj.weight", "transformer.h.7.attn.proj.bias", "transformer.h.7.mlp.fc.weight", "transformer.h.7.mlp.fc.bias", "transformer.h.7.mlp.proj.weight", "transformer.h.7.mlp.proj.bias", "transformer.h.8.attn.attn.weight", "transformer.h.8.attn.attn.bias", "transformer.h.8.attn.proj.weight", "transformer.h.8.attn.proj.bias", "transformer.h.8.mlp.fc.weight", "transformer.h.8.mlp.fc.bias", "transformer.h.8.mlp.proj.weight", "transformer.h.8.mlp.proj.bias", "transformer.h.9.attn.attn.weight", "transformer.h.9.attn.attn.bias", "transformer.h.9.attn.proj.weight", "transformer.h.9.attn.proj.bias", "transformer.h.9.mlp.fc.weight", "transformer.h.9.mlp.fc.bias", "transformer.h.9.mlp.proj.weight", "transformer.h.9.mlp.proj.bias", "transformer.h.10.attn.attn.weight", "transformer.h.10.attn.attn.bias", "transformer.h.10.attn.proj.weight", "transformer.h.10.attn.proj.bias", "transformer.h.10.mlp.fc.weight", "transformer.h.10.mlp.fc.bias", "transformer.h.10.mlp.proj.weight", "transformer.h.10.mlp.proj.bias", "transformer.h.11.attn.attn.weight", "transformer.h.11.attn.attn.bias", "transformer.h.11.attn.proj.weight", "transformer.h.11.attn.proj.bias", "transformer.h.11.mlp.fc.weight", "transformer.h.11.mlp.fc.bias", "transformer.h.11.mlp.proj.weight", "transformer.h.11.mlp.proj.bias", "transformer.h.12.attn.attn.weight", "transformer.h.12.attn.attn.bias", "transformer.h.12.attn.proj.weight", "transformer.h.12.attn.proj.bias", "transformer.h.12.mlp.fc.weight", "transformer.h.12.mlp.fc.bias", "transformer.h.12.mlp.proj.weight", "transformer.h.12.mlp.proj.bias", "transformer.h.13.attn.attn.weight", "transformer.h.13.attn.attn.bias", "transformer.h.13.attn.proj.weight", "transformer.h.13.attn.proj.bias", "transformer.h.13.mlp.fc.weight", "transformer.h.13.mlp.fc.bias", "transformer.h.13.mlp.proj.weight", "transformer.h.13.mlp.proj.bias", "transformer.h.14.attn.attn.weight", "transformer.h.14.attn.attn.bias", "transformer.h.14.attn.proj.weight", "transformer.h.14.attn.proj.bias", "transformer.h.14.mlp.fc.weight", "transformer.h.14.mlp.fc.bias", "transformer.h.14.mlp.proj.weight", "transformer.h.14.mlp.proj.bias", "transformer.h.15.attn.attn.weight", "transformer.h.15.attn.attn.bias", "transformer.h.15.attn.proj.weight", "transformer.h.15.attn.proj.bias", "transformer.h.15.mlp.fc.weight", "transformer.h.15.mlp.fc.bias", "transformer.h.15.mlp.proj.weight", "transformer.h.15.mlp.proj.bias".
```

**Comment by Andrei-Aksionov** [comment]
That's because you fine-tuned the model, but trying to run inference on a base model.

You need to provide `--checkpoint-dir` to the fine-tuned model weights, it should be something like:
> out/lora/alpaca/lit_model_lora_finetuned.pth

I'm doing it from my phone so might have provided not the correct path, but the idea should be clear.

**Comment by carmocca** [comment]
@Never-up I know what's the issue. I'll publish a PR quickly with the fix.

**Comment by avsanjay** [comment]
> @Never-up I know what's the issue. I'll publish a PR quickly with the fix.

Did this get published with the fix? I am facing the same issue
