### ISSUE TITLE
class 'lit_gpt.utils.NotYetLoadedTensor' does not have is_meta

### ISSUE THREAD

**Issue by lifengjin** [Lightning-AI/lit-gpt#432]
I am trying to run Llama 2 with fsdp and generate/base.py. When I turn on fsdp, it throws the following error:

```Traceback (most recent call last):
  File "xxxx/lit-gpt/generate/base.py", line 200, in <module>
    CLI(main)
  File "/opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "xxxx/lit-gpt/generate/base.py", line 153, in main
    model.load_state_dict(checkpoint.get("model", checkpoint), strict=quantize is None)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2138, in load_state_dict
    load(self, state_dict)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2120, in load
    module._load_from_state_dict(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2024, in _load_from_state_dict
    if param.is_meta and not input_param.is_meta and not assign_to_params_buffers:
  File "xxxx/lit-gpt/lit_gpt/utils.py", line 188, in __getattr__
    raise AttributeError(f"{type(self)} does not have {name}")
AttributeError: <class 'lit_gpt.utils.NotYetLoadedTensor'> does not have is_meta
```

**Comment by carmocca** [comment]
A recent change to Lightning Fabric broke this: https://github.com/Lightning-AI/lightning/pull/18122

Until we fix it, you can install a previous commit. This should work:

```shell
pip install git+https://github.com/Lightning-AI/lightning.git@c5cb53269465633076ad9220e225336ebb815547
```

**Comment by lifengjin** [comment]
Changing Fabric works. Closing the issue.
