### ISSUE TITLE
Llama-2 70b oom with 8 A100s

### ISSUE THREAD

**Issue by lifengjin** [Lightning-AI/lit-gpt#438]
I have been trying to run Llama-2 70b chat with 8 A100 GPUs with 40G of memory. The model is converted from HF with bf16 precision. I ran with this 
```
python generate/base.py --checkpoint_dir llama-2/hf/Llama-2-70b-chat-hf --prompt "who are you?" --strategy fsdp --devices 8 --precision bf16-true
```

and encountered this error every time:

```
[2023-08-18 06:49:27,313] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/8
[2023-08-18 06:49:33,000] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 06:49:33,061] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 06:49:33,223] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 06:49:33,272] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 06:49:33,385] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 06:49:33,423] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-08-18 06:49:33,435] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/8
Initializing distributed: GLOBAL_RANK: 5, MEMBER: 6/8
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/8
Initializing distributed: GLOBAL_RANK: 7, MEMBER: 8/8
Initializing distributed: GLOBAL_RANK: 4, MEMBER: 5/8
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/8
Initializing distributed: GLOBAL_RANK: 6, MEMBER: 7/8
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 8 processes
----------------------------------------------------------------------------------------------------

Loading model 'llama-2/hf/Llama-2-70b-chat-hf/lit_model.pth' with {'org': 'meta-llama', 'name': 'Llama-2-70b-chat-hf', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 64, 'padded_vocab_size': 32000, 'n_layer': 80, 'n_head': 64, 'n_embd': 8192, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 8, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'intermediate_size': 28672, 'condense_ratio': 1}
Time to instantiate model: 0.03 seconds.
Time to load the model weights: 497.58 seconds.
Traceback (most recent call last):
  File "lit-gpt/generate/base.py", line 200, in <module>
    CLI(main)
  File "/opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/apdcephfs/share_300000800/user/lifengjin/diagnosis_fix/generate/base.py", line 157, in main
    model = fabric.setup_module(model)
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 274, in setup_module
    module = self._strategy.setup_module(module)
  File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/strategies/fsdp.py", line 273, in setup_module
    module = FullyShardedDataParallel(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 456, in __init__
    _auto_wrap(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 72, in _auto_wrap
    _post_order_apply(root_module, wrap_fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 79, in _post_order_apply
    _post_order_apply_inner(root_module, "", None)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 63, in _post_order_apply_inner
    _post_order_apply_inner(child_module, child_module_name, module)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 63, in _post_order_apply_inner
    _post_order_apply_inner(child_module, child_module_name, module)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 63, in _post_order_apply_inner
    _post_order_apply_inner(child_module, child_module_name, module)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 64, in _post_order_apply_inner
    optional_module = fn(module)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/wrap.py", line 98, in fn
    return fsdp_fn(module, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 480, in __init__
    _init_param_handle_from_module(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 519, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/_init_utils.py", line 543, in _init_param_handle_from_params
    handle.shard()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/flat_param.py", line 857, in shard
    sharded_flat_param, numel_padded = FlatParamHandle._get_shard(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/flat_param.py", line 1017, in _get_shard
    shard = chunk.clone()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 206.00 MiB. GPU 7 has a total capacty of 39.59 GiB of which 86.19 MiB is free. Process 206076 has 22.24 GiB memory in use. Process 829590 has 17.26 GiB memory in use. Of the allocated memory 16.14 GiB is allocated by PyTorch, and 133.68 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by lifengjin** [comment]
This is caused by https://github.com/pytorch/pytorch/issues/105840 . This issue indicates that FSDP loads the model file into CPU memory first. For 8 GPUs, the model will be loaded 8 times, causing 70B models to go oom on CPU. The corrupted environment subsequently caused follow-up runs to go oom on GPUs.

**Comment by MrJungle1** [comment]
@lifengjin Hello, please tell me how you solved it. I also encountered the same problem. Thanks!
