### ISSUE TITLE
save_lora_checkpoint: TypeError: Fabric.save() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by OscarIntellico** [Lightning-AI/lit-gpt#453]
Hi guys,
I'm finetuning LLama2, but i noticed this problem while tinkering with the adapters in the past.
When a checkpoint is saved during the training or at the end, the following line raises an exception:
```fabric.save(file_path, {"model": model}, filter={"model": lora_filter})```
I tried to solve this by removing the filter, but it doesn't work when i try to run the finetune model with **generate/lora.py**.

The error is: 
```Traceback (most recent call last):
  File "/home/ubuntu/lit-parrot/finetune/lora.py", line 390, in <module>
    CLI(setup)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/ubuntu/lit-parrot/finetune/lora.py", line 104, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir, quantize)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 759, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 841, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 846, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/ubuntu/lit-parrot/finetune/lora.py", line 172, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/home/ubuntu/lit-parrot/finetune/lora.py", line 298, in train
    save_lora_checkpoint(fabric, model, checkpoint_path)
  File "/home/ubuntu/lit-parrot/finetune/lora.py", line 380, in save_lora_checkpoint
    fabric.save(file_path, {"model": model}, filter={"model": lora_filter})
TypeError: Fabric.save() got an unexpected keyword argument 'filter'```

**Comment by OscarIntellico** [comment]
Issue solved, i had an old version of torch-lightning, i just had to reinstall the requirements with
`pip install -r requirements.txt --upgrade`
