### ISSUE TITLE
lm_eval_harness.py: unexpected keyword argument 'max_new_tokens'

### ISSUE THREAD

**Issue by shin-ee-chen** [Lightning-AI/lit-gpt#508]
Use lm_eval_harness.py to evaluate Llama2 on gsm8k. The error output is:
Traceback (most recent call last):
  File "/gpfs/work5/0/gusr0608/neurips/lit-gpt/eval/lm_eval_harness.py", line 252, in <module>
    result = CLI(run_eval_harness)
  File "/home/xchen/.conda/envs/neurips2023-1/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/xchen/.conda/envs/neurips2023-1/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/gpfs/work5/0/gusr0608/neurips/lit-gpt/eval/lm_eval_harness.py", line 232, in run_eval_harness
    results = eval_harness.run_eval(
  File "/home/xchen/.conda/envs/neurips2023-1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/gpfs/work5/0/gusr0608/neurips/lit-gpt/eval/lm_eval_harness.py", line 182, in run_eval
    results = evaluator.evaluate(
  File "/gpfs/work5/0/gusr0608/neurips/lm-evaluation-harness/lm_eval/utils.py", line 243, in _wrapper
    return fn(*args, **kwargs)
  File "/gpfs/work5/0/gusr0608/neurips/lm-evaluation-harness/lm_eval/evaluator.py", line 305, in evaluate
    resps = getattr(lm, reqtype)([req.args for req in reqs])
  File "/gpfs/work5/0/gusr0608/neurips/lm-evaluation-harness/lm_eval/base.py", line 453, in greedy_until
    cont = self._model_generate(
  File "/gpfs/work5/0/gusr0608/neurips/lit-gpt/eval/lm_eval_harness.py", line 128, in _model_generate
    out = generate(
  File "/home/xchen/.conda/envs/neurips2023-1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: generate() got an unexpected keyword argument 'max_new_tokens'

The arguments are:
 python eval/lm_eval_harness.py \
   --checkpoint_dir "checkpoints/huggingface/Llama-2-7b-hf" \
   --precision "bf16-true" \
   --eval_tasks "[gsm8k]" \
   --batch_size 4 \
   --save_filepath "results-openllama-7b.json"

**Comment by Zhipeng-Xu** [comment]
I have the same problem.
