### ISSUE TITLE
TypeError: Config.__init__() got an unexpected keyword argument 'rope_n_elem'

### ISSUE THREAD

**Issue by HelenGuohx** [Lightning-AI/lit-gpt#534]
Hi there,

I got this error while trying with Falcon 7B model on Google Colab T4 GPU with high RAM enabled. 

```
!python generate/base.py \
    --prompt "I am so fast that I can" \
    --checkpoint_dir 'checkpoints/tiiuae/falcon-7b' \
    --max_new_tokens 50 \
    --precision "32-true"
```

Error message ```
Traceback (most recent call last):
  File "/content/lit-gpt/generate/base.py", line 184, in <module>
    CLI(main)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/content/lit-gpt/generate/base.py", line 126, in main
    config = Config.from_json(checkpoint_dir / "lit_config.json")
  File "/content/lit-gpt/lit_gpt/config.py", line 102, in from_json
    return cls(**json_kwargs)
TypeError: Config.__init__() got an unexpected keyword argument 'rope_n_elem'```

**Comment by carmocca** [comment]
Hi! Thanks for reporting

#535 will fix this. In the meantime, you can remove the `rope_n_elem` attribute that's set inside `checkpoints/tiiuae/falcon-7b/lit_config.json`
