### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by ARROGANT666** [Lightning-AI/lit-gpt#554]
"When I ran the finetune code, I encountered the following issue."
(myproject) wzp@ubuntu:~/lit-gpt-main$ python /home/wzp/lit-gpt-main/finetune/lora-codecomment2code.py --precision "bf16-true" --quantize "bnb.nf4-dq"
/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
Traceback (most recent call last):
  File "/home/wzp/lit-gpt-main/finetune/lora-codecomment2code.py", line 345, in <module>
    CLI(setup)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/wzp/lit-gpt-main/finetune/lora-codecomment2code.py", line 102, in setup
    logger = step_csv_logger(out_dir.parent, out_dir.name, flush_logs_every_n_steps=log_interval)
  File "/home/wzp/lit-gpt-main/lit_gpt/utils.py", line 443, in step_csv_logger
    logger.experiment.save = MethodType(save, logger.experiment)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/lightning-2.1.0rc0-py3.9.egg/lightning/fabric/loggers/logger.py", line 118, in experiment
    return fn(self)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/lightning-2.1.0rc0-py3.9.egg/lightning/fabric/loggers/csv_logs.py", line 128, in experiment
    self._experiment = _ExperimentWriter(log_dir=self.log_dir)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/lightning-2.1.0rc0-py3.9.egg/lightning/fabric/loggers/csv_logs.py", line 199, in __init__
    self._fs.makedirs(self.log_dir, exist_ok=True)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/site-packages/fsspec/implementations/local.py", line 54, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/home/wzp/anaconda3/envs/myproject/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/wzp/lit-gpt-main/out/lora/Tufano_codecomment-to-code/version_1'

**Comment by carmocca** [comment]
Have you checked that you have write permissions to that directory?
