### ISSUE TITLE
NotImplementedError while lora finetiuning

### ISSUE THREAD

**Issue by ian00000** [Lightning-AI/lit-gpt#559]
I ran into NotImplementedError while finetiuning vicuna-7b-v1.5 with lora
I ran:

!python finetune/lora.py --data_dir data --out_dir out --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.5 --precision bf16-true

The cell says:

```python
Using bfloat16 Automatic Mixed Precision (AMP)
{'eval_interval': 100, 'save_interval': 100, 'eval_iters': 100, 'eval_max_new_tokens': 100, 'log_interval': 1, 'devices': 1, 'learning_rate': 0.0003, 'batch_size': 128, 'micro_batch_size': 4, 'gradient_accumulation_iters': 32, 'max_iters': 50000, 'weight_decay': 0.01, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, 'lora_query': True, 'lora_key': False, 'lora_value': True, 'lora_projection': False, 'lora_mlp': False, 'lora_head': False, 'warmup_steps': 100}
Global seed set to 1337
Loading model 'checkpoints/lmsys/vicuna-7b-v1.5/lit_model.pth' with {'org': 'lmsys', 'name': 'vicuna-7b-v1.5', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 64, 'padded_vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'intermediate_size': 11008, 'rope_condense_ratio': 1, 'rope_base': 10000, 'r': 8, 'alpha': 16, 'dropout': 0.05, 'to_query': True, 'to_key': False, 'to_value': True, 'to_projection': False, 'to_mlp': False, 'to_head': False, 'head_size': 128, 'rope_n_elem': 128}
Number of trainable parameters: 4,194,304
Number of non trainable parameters: 6,738,415,616
Global seed set to 1337
Validating ...
Recommend a movie for me to watch during the weekend and explain the reason.
Traceback (most recent call last):
  File "/content/lit-gpt/finetune/lora.py", line 329, in <module>
    CLI(setup)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/content/lit-gpt/finetune/lora.py", line 90, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir, quantize)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/content/lit-gpt/finetune/lora.py", line 145, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/content/lit-gpt/finetune/lora.py", line 169, in train
    validate(fabric, model, val_data, tokenizer, longest_seq_length)  # sanity check
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/lit-gpt/finetune/lora.py", line 266, in validate
    output = generate(model, encoded, max_returned_tokens=len(encoded) + eval_max_new_tokens, temperature=0.8)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/lit-gpt/generate/base.py", line 47, in generate
    raise NotImplementedError(f"max_seq_length {model.max_seq_length} needs to be < {max_returned_tokens - 1}")
NotImplementedError: max_seq_length 57 needs to be < 151
```

**Comment by zrx-kishore-rajendran** [comment]
facing the same error

**Comment by carmocca** [comment]
If `max_seq_length` is 57 (and you haven't set `override_max_seq_length=57`), then it means that the longest sample length of your dataset is 57.

By default, the validation code tries to generate a sample for https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/lora.py#L258. The default is to generate 100 extra tokens: https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/lora.py#L34. Making it a total of 151

Since your `max_seq_length` is very short, you can make `eval_max_new_tokens` smaller. 6 (57-(151-100)) would be the maximum value you can set
