### ISSUE TITLE
For ‘auto’ strategy, how can I use Activation Checkpointing and Parameter Offloading(like FSDPStrategy)?

### ISSUE THREAD

**Issue by ifshine** [Lightning-AI/lit-gpt#570]
Thanks for your excellent work! Question in title. (Because I want to train a model on a single GPU)

```
    if fabric_devices > 1:
        strategy = FSDPStrategy(
            auto_wrap_policy={Block},
            activation_checkpointing_policy={Block},
            state_dict_type="full",
            limit_all_gathers=True,
            cpu_offload=False,
        )
    else:
        strategy = "auto"
```

**Comment by carmocca** [comment]
These arguments are specific to FSDP, so they are not available when "auto" is used.

**Comment by carmocca** [comment]
Mmm I thought FSDP didn't allow using a single device, but I just tried and it runs. However, I don't know if CPU offloading on a single device will work as expected. It would be interesting to check this in with the memory profiler. cc @awaelchli in case you know about this already

**Comment by ifshine** [comment]
> You don't get the advantages of sharding and data parallelism, but I think you could use FSDP on a single GPU though, @carmocca ? I.e., if you only care about CPU offloading, I think you can do
> 
> ```python
>         strategy = FSDPStrategy(
>             auto_wrap_policy={Block},
>             activation_checkpointing_policy={Block},
>             ...
>             cpu_offload=True,
> ```
> 
> and
> 
> ```python
> fabric = Fabric(... devices=1, strategy=strategy)
> ```

I appreciate your advice! But an error is reported as below.
![image](https://github.com/Lightning-AI/lit-gpt/assets/47179231/8aad64ce-4fb5-4f5a-95d6-bd41848ad0c7)

**Comment by ifshine** [comment]
Thanks for all of your advice!😄

```
            strategy = FSDPStrategy(
            auto_wrap_policy={Block},
            activation_checkpointing_policy={Block},
            ...
            cpu_offload=True,
```

 Above code can work for a single gpu.
 I want to use activation_checkpointing and cpu_offload to save gpu memory.
 
I finetune llama2-7b with LIMA(epoch=1, bf16-true, max_seq_len=1024, micro_batch_size=1, strategy = "auto"). It requires 18.68 GB(gpu memory) and 123.81s training time.
 However, the using of FSDPStrategy in a single gpu requires 27.22 GB(gpu memory) and 1546.70s training time.
 So strange.....

**Comment by carmocca** [comment]
I briefly tried running the above but got an error

```python
Non-root FSDP instance's `_is_root` should not have been set yet or should have been set to `False`
  File "/home/carlos/lit-parrot/finetune/lora.py", line 327, in <module>
    CLI(setup)
  File "/home/carlos/venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/carlos/venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 82, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir, quantize)
  File "/home/carlos/lightning/src/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/fabric.py", line 919, in _wrap_and_launch
    return launcher.launch(to_run, *args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/strategies/launchers/subprocess_script.py", line 101, in launch
    return function(*args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 143, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 167, in train
    validate(fabric, model, val_data, tokenizer, longest_seq_length)  # sanity check
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 251, in validate
    logits = model(input_ids)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/wrappers.py", line 122, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 844, in forward
    args, kwargs = _root_pre_forward(self, self, args, kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 539, in _root_pre_forward
    _lazy_init(state, module)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 171, in _lazy_init
    _share_state_and_init_handle_attrs(state, root_module)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 239, in _share_state_and_init_handle_attrs
    _p_assert(
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/utils.py", line 145, in _p_assert
    traceback.print_stack()
Traceback (most recent call last):
  File "/home/carlos/lit-parrot/finetune/lora.py", line 327, in <module>
    CLI(setup)
  File "/home/carlos/venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/carlos/venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 82, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir, quantize)
  File "/home/carlos/lightning/src/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/fabric.py", line 919, in _wrap_and_launch
    return launcher.launch(to_run, *args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/strategies/launchers/subprocess_script.py", line 101, in launch
    return function(*args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 143, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 167, in train
    validate(fabric, model, val_data, tokenizer, longest_seq_length)  # sanity check
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/carlos/lit-parrot/finetune/lora.py", line 251, in validate
    logits = model(input_ids)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carlos/lightning/src/lightning/fabric/wrappers.py", line 122, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 844, in forward
    args, kwargs = _root_pre_forward(self, self, args, kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 539, in _root_pre_forward
    _lazy_init(state, module)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 171, in _lazy_init
    _share_state_and_init_handle_attrs(state, root_module)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 239, in _share_state_and_init_handle_attrs
    _p_assert(
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/utils.py", line 147, in _p_assert
    raise AssertionError(s)
AssertionError: Non-root FSDP instance's `_is_root` should not have been set yet or should have been set to `False`
```

@ifshine Since this is uncharted territory, could you open a new issue in the https://github.com/Lightning-AI/lightning repository requesting that this is supported/explored?

**Comment by ifshine** [comment]
Thanks! [Here](https://github.com/Lightning-AI/lit-gpt/issues/594) is a new issue.
