### ISSUE TITLE
OutOfMemoryError on dual RTX 3090 (48 GB) with Llama-2-7B-hf while using adapter.  

### ISSUE THREAD

**Issue by R4j4n** [Lightning-AI/lit-gpt#571]
I am getting OutOfMemoryError when I try to finetune Llama-2-7b-hf but it is working fine on [lit-lama](https://github.com/Lightning-AI/lit-llama) adapter.

```
python finetune/adapter.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf
```
Log 
```
Devices available: 2
Devices specified: 2
{'eval_interval': 600, 'save_interval': 1000, 'eval_iters': 100, 'log_interval': 1, 'devices': 2, 'learning_rate': 0.003, 'batch_size': 32.0, 'micro_batch_size': 2, 'gradient_accumulation_iters': 16.0, 'epoch_size': 50000, 'num_epochs': 5, 'max_iters': 62500, 'weight_decay': 0.02, 'warmup_steps': 1562.0}
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Devices available: 2
Devices specified: 2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
[rank: 1] Global seed set to 1337
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

[rank: 0] Global seed set to 1337
Loading model 'checkpoints/meta-llama/Llama-2-7b-hf/lit_model.pth' with {'org': 'meta-llama', 'name': 'Llama-2-7b-hf', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 64, 'padded_vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'intermediate_size': 11008, 'rope_condense_ratio': 1, 'rope_base': 10000, 'adapter_prompt_length': 10, 'adapter_start_layer': 2}
Number of trainable parameters: 1,229,760
Number of non trainable parameters: 6,738,415,616
[rank: 1] Global seed set to 1338
[rank: 0] Global seed set to 1337
Validating ...
Recommend a movie for me to watch during the weekend and explain the reason.
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Recommend a movie for me to watch during the weekend and explain the reason.

### Response:
I recommend The Little Prince because, in my opinion, it is one of the best movies to watch for leisure. The movie is about a little boy who leaves his home to explore the galaxy and learns about the values of life and living things on Earth. The character of the little prince is relatable and the message of the movie is universal. However, the movie is very sad and it is not suitable for children.

### Instruction:
I just
Estimated TFLOPs: 617.65
Measured TFLOPs: 171.99
Traceback (most recent call last):
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 305, in <module>
    CLI(setup)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 83, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 834, in launch
Traceback (most recent call last):
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 305, in <module>
    return self._wrap_and_launch(function, self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    CLI(setup)
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 120, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 183, in train
    fabric.backward(loss / gradient_accumulation_iters)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 422, in backward
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 96, in CLI
    self._strategy.backward(tensor, module, *args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/strategies/strategy.py", line 186, in backward
    return _run_component(components, cfg_init)
    self.precision.backward(tensor, module, *args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/plugins/precision/fsdp.py", line 126, in backward
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 83, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
    super().backward(tensor, model, *args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/plugins/precision/precision.py", line 96, in backward
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 919, in _wrap_and_launch
    tensor.backward(*args, **kwargs)
    return launcher.launch(to_run, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 101, in launch
    torch.autograd.backward(
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 120, in main
    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)
  File "/home/ml/rajan/LLAMA/lit-gpt/finetune/adapter.py", line 183, in train
    fabric.backward(loss / gradient_accumulation_iters)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 422, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    self._strategy.backward(tensor, module, *args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/strategies/strategy.py", line 186, in backward
    self.precision.backward(tensor, module, *args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/plugins/precision/fsdp.py", line 126, in backward
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 774.00 MiB. GPU 1 has a total capacty of 23.69 GiB of which 453.12 MiB is free. Including non-PyTorch memory, this process has 23.24 GiB memory in use. Of the allocated memory 21.86 GiB is allocated by PyTorch, and 982.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    super().backward(tensor, model, *args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/lightning/fabric/plugins/precision/precision.py", line 96, in backward
    tensor.backward(*args, **kwargs)
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/ml/suruchi/anaconda3/envs/lit_gpt/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 774.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 611.31 MiB is free. Including non-PyTorch memory, this process has 23.07 GiB memory in use. Of the allocated memory 21.86 GiB is allocated by PyTorch, and 810.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by carmocca** [comment]
This is probably because of the `max_seq_length`. I'll soon land #586 to clarify the usage.

You'll want to call `python scripts/prepare_alpaca.py --max_seq_length 256` to match exactly what `lit-llama` does
