### ISSUE TITLE
Llama-2-70b-hf convert_hf_checkpoint.py shape RuntimeError

### ISSUE THREAD

**Issue by hfvienna** [Lightning-AI/lit-gpt#577]
When running `python3 scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/meta-llama/Llama-2-70b-hf` it loads until it runs into the following error: 

`Loading 'model.layers.4.post_attention_layernorm.weight' into RAM
Loading 'model.layers.5.self_attn.o_proj.weight' into RAM
Loading 'model.layers.5.mlp.gate_proj.weight' into RAM
Loading 'layer 0 q' into RAM
Loading 'layer 0 k' into RAM
Loading 'layer 0 v' into RAM
Traceback (most recent call last):
  File "scripts/convert_hf_checkpoint.py", line 306, in <module>
    CLI(convert_hf_checkpoint)
  File "/root/venv-lit-gpt/lib/python3.8/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/root/venv-lit-gpt/lib/python3.8/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/root/venv-lit-gpt/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "scripts/convert_hf_checkpoint.py", line 297, in convert_hf_checkpoint
    copy_fn(sd, hf_weights, saver=saver, dtype=dtype)
  File "scripts/convert_hf_checkpoint.py", line 168, in copy_weights_hf_llama
    qkv = qkv.reshape(config.n_embd * 3, -1)
RuntimeError: shape '[24576, -1]' is invalid for input of size 83886080
(venv-lit-gpt) root`

What causes this?

Additional info:
1. The GPU is A100 80GB, 700GB harddrive, so plenty
2. Using exactly the same process and GPU, 7b and 13b convert&run just fine.
3. No changes to the lit-gpt code were made.

**Comment by carmocca** [comment]
I'll fix this. Sorry for the inconvenience!

Checking out this commit: https://github.com/Lightning-AI/lit-gpt/commit/966646a428546360a9857ac7814869cc72ff6edb should work too
