### ISSUE TITLE
Support of Mistral-7B

### ISSUE THREAD

**Issue by Jeronymous** [Lightning-AI/lit-gpt#597]
Hello and thanks for the great work in lit-gpt :)

Is there any plan to include [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1)?

```
python lit_gpt/scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/mistralai/Mistral-7B-v0.1
Traceback (most recent call last):
  File "/gpfs7kw/linkhome/rech/gendjf01/uov59an/src/Claire/lit_gpt/scripts/convert_hf_checkpoint.py", line 306, in <module>
    CLI(convert_hf_checkpoint)
  File "/linkhome/rech/gendjf01/uov59an/.local/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/linkhome/rech/gendjf01/uov59an/.local/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/linkhome/rech/gendjf01/uov59an/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/gpfs7kw/linkhome/rech/gendjf01/uov59an/src/Claire/lit_gpt/scripts/convert_hf_checkpoint.py", line 257, in convert_hf_checkpoint
    config = Config.from_name(model_name)
  File "/gpfs7kw/linkhome/rech/gendjf01/uov59an/src/Claire/lit_gpt/lit_gpt/config.py", line 85, in from_name
    conf_dict = name_to_config[name].copy()
KeyError: 'Mistral-7B-v0.1'

```

**Comment by carmocca** [comment]
Yes. It's in progress in https://github.com/Lightning-AI/lit-gpt/compare/main...carmocca/mistral

However, we will only support up to 4k tokens to avoid implementing Sliding Window attention only for this checkpoint. We might support the extended context length if more checkpoints start using it from now on.

**Comment by abzb1** [comment]
What is the current status of the implementation of sliding windows?

**Comment by carmocca** [comment]
There is no plan to implement it. Mixtral and Mistral v0.2 doesnt use it anymore too
