### ISSUE TITLE
LoRA merge bug when enabling more hyperparameters

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#629]
I am getting a bug with the merging if you change the default parameters in LoRA.

Everything works fine with the defaults, but when changing the following (`lora_key = False  --> True`), 

```python
max_iters = 50000  # train dataset size
weight_decay = 0.01
lora_r = 8
lora_alpha = 16
lora_dropout = 0.05
lora_query = True
lora_key = False  --> True
lora_value = True
lora_projection = False
lora_mlp = False
lora_head = False
warmup_steps = 100
```

with

```bash
python finetune/lora.py   \
  --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/  \
  --precision "bf16-true"    \
  --data_dir out/alpaca/Llama-2-7b-hf    \
  --out_dir out/lora/alpaca/Llama-2-7b-hf \
  --quantize "bnb.nf4"
```

it results in a 

```bash
iter 49990 step 390: loss 1.3699, iter time: 163.44ms 
iter 49991 step 390: loss 0.8315, iter time: 157.93ms 
iter 49992 step 390: loss 1.1475, iter time: 158.00ms 
iter 49993 step 390: loss 0.4026, iter time: 146.42ms 
iter 49994 step 390: loss 0.7851, iter time: 162.92ms 
iter 49995 step 390: loss 0.5721, iter time: 144.87ms 
iter 49996 step 390: loss 0.7765, iter time: 158.20ms 
iter 49997 step 390: loss 0.8009, iter time: 150.48ms 
iter 49998 step 390: loss 0.6623, iter time: 144.75ms 
iter 49999 step 390: loss 1.8696, iter time: 158.91ms 
Training time: 9418.35s
Memory used: 13.53 GB
Saving LoRA weights to 'out/lora/alpaca/Llama-2-7b-hf/lit_model_lora_finetuned.pth'
(new-lit) sebastian@hyperplane1:~/Developer/prs/experiments/lit-gpt$ python scripts/merge_lora.py    --checkpoint_dir "checkpoints/meta-llama/Llama-2-7b-hf/"    --lora_path "out/lora/alpaca/Llama-2-7b-hf/lit_model_lora_finetuned.pth"    --out_dir "out/lora_merged/Llama-2-7b-hf/"                                           
Traceback (most recent call last):
  File "/home/sebastian/Developer/prs/experiments/lit-gpt/scripts/merge_lora.py", line 82, in <module>
    CLI(merge_lora)
  File "/home/sebastian/miniforge3/envs/new-lit/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/sebastian/miniforge3/envs/new-lit/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/sebastian/Developer/prs/experiments/lit-gpt/scripts/merge_lora.py", line 68, in merge_lora
    model.load_state_dict(checkpoint)
  File "/home/sebastian/miniforge3/envs/new-lit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GPT:
        size mismatch for transformer.h.0.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.0.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.1.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.1.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.2.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.2.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.3.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.3.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.4.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.4.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.5.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.5.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.6.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.6.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.7.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.7.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.8.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.8.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.9.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.9.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.10.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.10.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.11.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.11.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.12.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.12.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.13.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.13.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.14.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.14.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.15.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.15.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.16.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.16.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.17.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.17.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.18.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.18.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.19.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.19.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.20.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.20.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.21.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.21.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.22.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.22.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.23.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.23.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.24.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.24.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.25.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.25.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.26.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.26.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.27.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.27.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.28.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.28.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.29.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.29.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.30.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
        size mismatch for transformer.h.30.attn.attn.lora_B: copying a param with shape torch.Size([12288, 8]) from checkpoint, the shape in current model is torch.Size([8192, 8]).
        size mismatch for transformer.h.31.attn.attn.lora_A: copying a param with shape torch.Size([24, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096]).
(new-lit) sebastian@hyperplane1:~/Developer/prs/experiments/lit-gpt$ 
```

**Comment by rasbt** [comment]
At first, I thought that this was an issue with grouped attention in Llama 2, but I was able to reproduce the issue with the default Stable LM:


```bash
python finetune/lora.py

python scripts/merge_lora.py \
   --checkpoint_dir "checkpoints/stabilityai/stablelm-base-alpha-3b/" \
   --lora_path "out/lora/alpaca/lit_model_lora_finetuned.pth" \
   --out_dir "out/"
```

and even Pythia:

```bash
python finetune/lora.py --checkpoint_dir checkpoints/EleutherAI/pythia-70m

python scripts/merge_lora.py \
   --checkpoint_dir "checkpoints/EleutherAI/pythia-70m" \
   --lora_path "out/lora/alpaca/lit_model_lora_finetuned.pth" \
   --out_dir "out/"
```

I tried other LoRA hparam settings and they also fail:

- `lora_head = True` -> Unexpected key(s) in state_dict: "lm_head.lora_A", "lm_head.lora_B". 
- `lora_mlp = True` -> ... Unexpected key(s) in state_dict: "transformer.h.0.mlp.fc.lora_A",
- `lora_projection = True` -> `  Unexpected key(s) in state_dict: "transformer.h.0.attn.proj.lora_A", `
- changing the `r` to anything but 8 ->  size mismatch for transformer.h.0.attn.attn.lora_A: copying a param with shape torch.Size([32, 512]) ...

**Comment by rasbt** [comment]
This is because I forgot to edit the `merge_lora.py` script configuration accordingly. (Related: https://github.com/Lightning-AI/lit-gpt/issues/483)
