### ISSUE TITLE
pretrain/openwebtext.py does not work on GPU

### ISSUE THREAD

**Issue by gkroiz** [Lightning-AI/lit-gpt#640]
I ran into several issues when trying to run `pretrain/openwebtext.py` on 4 GPUs.

1) Tutorial recommends arg `--train_data_dir` when running `pretrain/openwebtext.py` (https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/pretrain_openwebtext.md?plain=1#L105). However, this is not a valid argument for `pretrain/openwebtext.py` (https://github.com/Lightning-AI/lit-gpt/blob/main/pretrain/openwebtext.py#L53)

2) Similar to the issue above, in `pretrain/openwebtext.py`, `name="openwebtext"` (https://github.com/Lightning-AI/lit-gpt/blob/main/pretrain/openwebtext.py#L25). However, this should be `name="lit-openwebtext"` since that is where the data is saved.

If (1) is resolved, it would also resolve (2)

3) This issue isn't as trivial as the other two. When training on 4 devices, I get an FSDP-related assertion error 
```AssertionError: The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook```
If it makes more sense, we can create a separate issue just for (3).

Full logs are shared below. Some important setup details:

- GPUS: 4 x NVIDIA L4 (also tested on NVIDIA A100s)
- Torch version: 2.1.0+cu121
- Lightning version: 2.1.0.rc0
- CUDA version: 12.0
- NVIDIA Driver version: 525.125.06

Also, (1) and (2) are also observed for `pretrain/openwebtext_trainer.py` but not (3).

```
gersonkroiz@gersonkroiz-gpu-do-not-delete:~/lit-gpt$ python3 pretrain/openwebtext.py   --devices 4
{'model_name': 'pythia-70m', 'name': 'lit-openwebtext', 'save_interval': 10, 'eval_interval': 1000, 'eval_iters': 100, 'log_interval': 1, 'learning_rate': 0.0006, 'batch_size': 125, 'micro_batch_size': 5, 'gradient_accumulation_steps': 25, 'max_iters': 600000, 'weight_decay': 0.1, 'beta1': 0.9, 'beta2': 0.95, 'grad_clip': 1.0, 'decay_lr': True, 'warmup_iters': 2000, 'lr_decay_iters': 600000, 'min_lr': 6e-05}
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

[rank: 0] Seed set to 1337
Loading model with {'org': 'EleutherAI', 'name': 'pythia-70m', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 6, 'n_head': 8, 'n_embd': 512, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'lm_head_bias': False, 'n_query_groups': 8, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'gelu_approximate': 'none', 'intermediate_size': 2048, 'rope_condense_ratio': 1, 'rope_base': 10000, 'head_size': 64, 'rope_n_elem': 16}
Time to instantiate model: 0.02 seconds.
Total parameters 70,426,624
Memory before model setup: 0.00 GB
[rank: 1] Seed set to 1337
[rank: 2] Seed set to 1337
[rank: 3] Seed set to 1337
Memory after model setup: 0.07 GB
Memory after optimizers setup: 0.07 GB
Memory before training: 0.07 GB
Validating ...
Estimated TFLOPs: 22.46
Measured TFLOPs: 14.06
Memory before forward step: 0.29 GB
The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    CLI(setup)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 145, in _p_assert
    traceback.print_stack()
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    CLI(setup)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    CLI(setup)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 145, in _p_assert
    traceback.print_stack()
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 145, in _p_assert
    traceback.print_stack()
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    CLI(setup)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 919, in _wrap_and_launch
    return launcher.launch(to_run, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 104, in launch
    return function(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 145, in _p_assert
    traceback.print_stack()
Traceback (most recent call last):
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    CLI(setup)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
Traceback (most recent call last):
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    return _run_component(components, cfg_init)
Traceback (most recent call last):
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    CLI(setup)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    CLI(setup)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return _run_component(components, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
Traceback (most recent call last):
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 263, in <module>
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    CLI(setup)
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    return _run_component(components, cfg_init)
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 181, in _run_component
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return to_run(*args, **kwargs)
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    return component(**cfg)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 69, in setup
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    fabric.launch(main, resume=resume)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 919, in _wrap_and_launch
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
    return launcher.launch(to_run, *args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/strategies/launchers/subprocess_script.py", line 104, in launch
    return function(*args, **kwargs)
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    return forward_call(*args, **kwargs)
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    return to_run(*args, **kwargs)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 112, in main
    _register_post_backward_hook(state, handle)
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 147, in _p_assert
    train(fabric, state, train_dataloader, val_dataloader, speed_monitor)
  File "/home/gersonkroiz/lit-gpt/pretrain/openwebtext.py", line 160, in train
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    raise AssertionError(s)
AssertionError: The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
    logits = model(input_ids)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 147, in _p_assert
    raise AssertionError(s)
AssertionError: The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 147, in _p_assert
    raise AssertionError(s)
AssertionError: The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 825, in forward
    args, kwargs = _pre_forward(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 433, in _pre_forward
    _register_post_backward_hook(state, handle)
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 1435, in _register_post_backward_hook
    _p_assert(
  File "/home/gersonkroiz/.local/lib/python3.9/site-packages/torch/distributed/utils.py", line 147, in _p_assert
    raise AssertionError(s)
AssertionError: The `grad_fn` is needed to access the `AccumulateGrad` and register the post-backward hook
```

**Comment by gkroiz** [comment]
For (3), I notice that when commenting out https://github.com/Lightning-AI/lit-gpt/blob/main/pretrain/openwebtext.py#L126, training is able to run.

**Comment by artnoage** [comment]
@gkroiz Do you mean removing the whole part? because if you remove just 126 the code makes no sense. If I remove everything related to 126 then indeed the training works. Did you figure the source of the error?

**Comment by artnoage** [comment]
I think it was the evaluation function validate(fabric, model, val_dataloader) that came before. Now it works for me. I opened a new issue anyway https://github.com/Lightning-AI/lit-gpt/issues/699

**Comment by carmocca** [comment]
1 and 2 should be fixed already by https://github.com/Lightning-AI/lit-gpt/commit/60c0938f3b4d8f0576ea7757bc6003cc9e3e6271

I'll address 3 with #699

Thank you for reporting these issues!
