### ISSUE TITLE
Quantization is currently not supported for multi-GPU training

### ISSUE THREAD

**Issue by kannangce** [Lightning-AI/lit-gpt#712]
I'm trying to lora finetune mistral using T4.

I got into this error(https://github.com/Lightning-AI/lit-gpt/issues/693) when trying to use 16-true precision.

So I increased the precision to 32-true. And had OOM error.

Then trying to workaround with 2GPUs by setting `device=2` in `lora.py`, following [this suggestion](https://github.com/Lightning-AI/lit-gpt/issues/660#issuecomment-1772654494).
Now getting the following error,

> Traceback (most recent call last):
  File "/content/llm-finetune/finetune/lora.py", line 338, in <module>
    CLI(setup)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/content/llm-finetune/finetune/lora.py", line 79, in setup
    raise NotImplementedError(
NotImplementedError: Quantization is currently not supported for multi-GPU training. Please set devices=1 when using the --quantize flag.

Any idea how can get this lora fine-tuning work with T4?

**Comment by Andrei-Aksionov** [comment]
Hello @kannangce 
Have you tried to play with `context length`?
https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/oom.md#reduce-the-models-context-length

**Comment by kannangce** [comment]
Hi @Andrei-Aksionov , 

I was able to make the fine-tuning work by minimizing the `micro_batch_size` to 2. But the time taken is too much.

I'm curious, if multiple GPUs with lora is not supported as per the error message, what does [this table](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/resource-tables.md#finetuning-with-lora-on-multiple-gpus) in the doc means?

**Comment by carmocca** [comment]
Multiple gpus are supported with LoRA. What isn't is QLoRA (aka quantization with LoRA): #449. You'll notice that the rows that enable quantization in that table show "N/A"

**Comment by lee-b** [comment]
From the error message: "Please set devices=1 when using the --quantize flag."

From what you said that you did: "workaround...by setting device=2 in lora.py"

**Comment by rasbt** [comment]
This is unfortunately a current implementation, but it may be addressed in the future via a new bnb version. Closing for now since it's also tracked here in #1175
