### ISSUE TITLE
Latest openwebtext_trainer throwing KeyError during eval

### ISSUE THREAD

**Issue by Chris113113** [Lightning-AI/lit-gpt#713]
I was running an older version of lit-gpt that had flash-attn enabled, and I'm now trying to update to the latest head.

I'm just using the `openwebtext_trainer.py` workflow, nothing special.

It's crashing during the first eval call.

lit-gpt commit: d9283f420be2ee3b9af77b2e12edf92aa200379e
Relevant Dockerfile snippet:

```
FROM nvcr.io/nvidia/pytorch:23.09-py3
RUN pip uninstall -y torch && pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
RUN pip install -r requirements.txt tokenizers sentencepiece ujson
RUN pip install nvidia-dlprof-pytorch-nvtx nvidia-pyindex nvidia-dlprof csvkit
```

Launching lit-gpt with:
`python /workspace/pretrain/openwebtext_trainer.py --devices=8`

This is a multi-node training run, world size 32.

Stack trace: 
```
Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  3.96it/s]/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py:433: It is recommended to use `self.log('val_loss', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
Epoch 0: |          | 1000/? [00:38<00:00, 25.66it/s, v_num=0, train_loss=7.550, val_loss=7.270]Traceback (most recent call last):
  File "/workspace/pretrain/openwebtext_trainer.py", line 200, in <module>
    CLI(main)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/workspace/pretrain/openwebtext_trainer.py", line 159, in main
    trainer.fit(model, train_dataloader, val_dataloader, ckpt_path="last")
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/evaluation_loop.py", line 141, in run
    return self.on_run_end()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/evaluation_loop.py", line 267, in on_run_end
    self._on_evaluation_end()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/evaluation_loop.py", line 308, in _on_evaluation_end
    call._call_callback_hooks(trainer, hook_name, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/throughput_monitor.py", line 201, in on_validation_end
    self._t0s[RunningStage.VALIDATING] - self._throughputs[RunningStage.TRAINING]._time[-1]
KeyError: <RunningStage.VALIDATING: 'validate'>
```

**Comment by carmocca** [comment]
Thanks for the report! I'll take a look. If you want, you can check out a previous version of the repo: https://github.com/Lightning-AI/lit-gpt/tree/60c0938f3b4d8f0576ea7757bc6003cc9e3e6271
