### ISSUE TITLE
Unable to infer with quantize param

### ISSUE THREAD

**Issue by kannangce** [Lightning-AI/lit-gpt#728]
I fine-tuned `mistralai/Mistral-7B-Instruct-v0.1` with params `--precision 32-true --quantize bnb.nf4`.

And when I try to infer using the below command,

```shell
python generate/lora.py --quantize bnb.nf4 \
 --checkpoint_dir checkpoints/$MODEL \
--lora_path=output/$MODEL/code-gen-ui/lit_model_lora_finetuned.pth \
--prompt "Add an accordian with size 2."
```

I'm getting the below output and error,
> Loading model 'checkpoints/mistralai/Mistral-7B-Instruct-v0.1/lit_model.pth' with {'org': 'mistralai', 'name': 'Mistral-7B-Instruct-v0.1', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 512, 'padded_vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 8, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'gelu_approximate': 'none', 'intermediate_size': 14336, 'rope_condense_ratio': 1, 'rope_base': 10000, 'r': 16, 'alpha': 32, 'dropout': 0.05, 'to_query': True, 'to_key': True, 'to_value': True, 'to_projection': True, 'to_mlp': True, 'to_head': True, 'head_size': 128, 'rope_n_elem': 128}
Time to instantiate model: 0.68 seconds.
Time to load the model weights: 30.80 seconds.
Traceback (most recent call last):
  File "/home/kannanr/llm-finetune/generate/lora.py", line 163, in <module>
    CLI(main)
  File "/home/kannanr/llm-finetune/myenv/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/kannanr/llm-finetune/myenv/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/kannanr/llm-finetune/generate/lora.py", line 129, in main
    merge_lora_weights(model)
  File "/home/kannanr/llm-finetune/lit_gpt/lora.py", line 659, in merge_lora_weights
    module.merge()
  File "/home/kannanr/llm-finetune/lit_gpt/lora.py", line 140, in merge
    self.linear.weight.data += (self.lora_B @ self.lora_A) * self.scaling
RuntimeError: The size of tensor a (65536000) must match the size of tensor b (32000) at non-singleton dimension 0

Whereas the inference work without `--quantize bnb.nf4` parameter passed to ` generate/lora.py`

Considering I passed the same `--quantize` param during the fine-tuning and inference, I don't expect to have an issue. Am I missing something?

**Comment by Andrei-Aksionov** [comment]
I was surprised to see this issue.
My understanding was that the weights are quantized when they are moved to CUDA device, which happens during `fabric.setup` call.

In `generate/lora.py` we first merge weights and then — move to device (quantize).
https://github.com/Lightning-AI/lit-gpt/blob/703de0220df99bc55569253505e9c5e62731b2ec/generate/lora.py#L129-L130

But when I quickly checked dtypes, it looks like the model is initialized with quantized weights already:
https://github.com/Lightning-AI/lit-gpt/blob/703de0220df99bc55569253505e9c5e62731b2ec/generate/lora.py#L117-L118

@carmocca Fabric's behavior has changed?

**Comment by carmocca** [comment]
@Andrei-Aksionov Fabric supports initializing the quantized model already on device instead of doing the slow cpu initialization first
