### ISSUE TITLE
Script to download models does not download .bin (falcon)

### ISSUE THREAD

**Issue by meanna** [Lightning-AI/lit-gpt#731]
I think something is wrong with scripts/download.py

I tried 
`python scripts/download.py --repo_id tiiuae/falcon-7b `
and 
`python scripts/download.py --repo_id stabilityai/stablelm-base-alpha-3b`

I found it doesn't download the actual model weights.
Here are what it downloads

```
$ ls checkpoints/stabilityai/stablelm-base-alpha-3b
generation_config.json  tokenizer.json  tokenizer_config.json

$ ls checkpoints/tiiuae/falcon-7b
generation_config.json  lit_config.json   tokenizer.json  tokenizer_config.json
```

Also, the library only works with python 3.10, because with python 3.8 and 3.9 there is a code incompatibility issue related to the use of | .
Maybe it is good to put this information in the README.

**Comment by carmocca** [comment]
I just fixed the download issue. Can you try updating `main`?

Can you also share the error that you get related to using `|`? We can change it to use `Union[...]`

**Comment by meanna** [comment]
Thank you so much for the quick fix. Yes, the download script works now.

The error was (or something similar to this)
`"Python version 3.8 does not allow writing union types as X | Y"`

I don't see the error anymore when using py thing 3.8 after pulling the latest change.

**Comment by meanna** [comment]
I found one more issue, 

When I run
`python scripts/convert_hf_checkpoint.py --checkpoint_dir stabilityai/stablelm-base-alpha-3b`

I get this error:
```
Model config {'name': 'stablelm-base-alpha-3b', 'hf_config': {'org': 'stabilityai', 'name': 'stablelm-base-alpha-3b'}, 'block_size': 4096, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 50688, 'n_layer': 16, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'lm_head_bias': False, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'gelu_approximate': 'none', 'intermediate_size': 16384, 'rope_condense_ratio': 1, 'rope_base': 10000}
Traceback (most recent call last):
  File "/content/lit-gpt/scripts/convert_hf_checkpoint.py", line 306, in <module>
    CLI(convert_hf_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/lit-gpt/scripts/convert_hf_checkpoint.py", line 261, in convert_hf_checkpoint
    with open(checkpoint_dir / "lit_config.json", "w") as json_config:
FileNotFoundError: [Errno 2] No such file or directory: 'stabilityai/stablelm-base-alpha-3b/lit_config.json'
```

Falcon 7b has lit_config.json downloaded and does not have this issue.

**Comment by meanna** [comment]
Does the library support fine-tuning on CPU?
I tried running `python finetune/adapter.py --checkpoint_dir checkpoints/tiiuae/falcon-7b/`
locally with CPU but it doesn't seem to fine-tune.

I only see this as output after a few minutes, the program terminates.
```

Using bfloat16 Automatic Mixed Precision (AMP)
{'eval_interval': 600, 'save_interval': 1000, 'eval_iters': 100, 'eval_max_new_tokens': 100, 'log_interval': 1, 'devices': 1, 'learning_rate': 0.003, 'b
atch_size': 64.0, 'micro_batch_size': 4, 'gradient_accumulation_iters': 16.0, 'epoch_size': 50000, 'num_epochs': 5, 'max_iters': 62500, 'weight_decay': 
0.02, 'warmup_steps': 1562.0}
Seed set to 1337
Loading model 'checkpoints\\tiiuae\\falcon-7b\\lit_model.pth' with {'name': 'falcon-7b', 'hf_config': {'org': 'tiiuae', 'name': 'falcon-7b'}, 'block_siz
e': 2048, 'vocab_size': 65024, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.
0, 'parallel_residual': True, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'nor
m_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'gelu_approximate': 'none', 'intermediate_size': 18176, 'rope_condense_ratio': 1, 'rope_base': 10000, 'adapte
r_prompt_length': 10, 'adapter_start_layer': 2, 'head_size': 64, 'rope_n_elem': 6
```4}

**Comment by carmocca** [comment]
It is technically supported but it would be unbearably slow unless it is a very small model (<100M parameters).

So I do not recommend it at all

**Comment by meanna** [comment]
I see. Thank you!
