### ISSUE TITLE
The weight map of phi_1_5 seems changed and not working

### ISSUE THREAD

**Issue by sanyalsunny111** [Lightning-AI/lit-gpt#760]
I am trying to use Phi 1_5, this is a recent change

python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/microsoft/phi-1_5

![image](https://github.com/Lightning-AI/lit-gpt/assets/36811567/9f1016c7-217e-4511-87c7-99e3bb4331de)

**Comment by Andrei-Aksionov** [comment]
Can confirm the problem, though I have a slightly different error:
```python
main ~/lit-gpt python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/microsoft/phi-1_5
Model config {'name': 'phi-1_5', 'hf_config': {'org': 'microsoft', 'name': 'phi-1_5'}, 'block_size': 2048, 'vocab_size': 50257, 'padding_multiple': 512, 'padded_vocab_size': 51200, 'n_layer': 24, 'n_head': 32, 'n_embd': 2048, 'rotary_percentage': 0.5, 'parallel_residual': True, 'bias': True, 'lm_head_bias': True, 'n_query_groups': 32, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'gelu_approximate': 'tanh', 'intermediate_size': 8192, 'rope_condense_ratio': 1, 'rope_base': 10000}
Processing checkpoints/microsoft/phi-1_5/pytorch_model.bin
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/lit-gpt/scripts/convert_hf_checkpoint.py", line 306, in <module>
    CLI(convert_hf_checkpoint)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/teamspace/studios/this_studio/lit-gpt/scripts/convert_hf_checkpoint.py", line 297, in convert_hf_checkpoint
    copy_fn(sd, hf_weights, saver=saver, dtype=dtype)
  File "/teamspace/studios/this_studio/lit-gpt/scripts/convert_hf_checkpoint.py", line 213, in copy_weights_phi
    to_name = weight_map[name]
KeyError: 'transformer.embd.wte.weight'
```

The latest main, the latest packages.

**Comment by carmocca** [comment]
I suspect that they broke compatibility: https://huggingface.co/microsoft/phi-1_5/commit/271c3397ab4e1f8f4e49868b1e8ba0be95363c88

Do you know if how we can ping to a specific hub version? Otherwise, this will require an update

**Comment by Andrei-Aksionov** [comment]
[`huggingface_hub.snapshot_download`](https://github.com/Lightning-AI/lit-gpt/blob/3fc3337acb73a272c9cae09a770bcebe1475cc0a/scripts/download.py#L53) has `revision` argument.

> revision (str, optional) — An optional Git revision id which can be a branch name, a tag, or a commit hash.

So I guess it's possible.

**Comment by carmocca** [comment]
Would you like to add an `if phi: pass x revision` to the script to unblock? We can keep this issue open until it's updated

**Comment by Andrei-Aksionov** [comment]
Sure.
