### ISSUE TITLE
ERROR: TPU initialization failed: Invalid --2a886c8_slice_builder_worker_addresses specified. Expected 4 worker addresses, got 1

### ISSUE THREAD

**Issue by IvoryTower800** [Lightning-AI/lit-gpt#866]
Hi, I'm new to this lit-gpt. it seems great for finetuning LLM on TPU.

I read the tutorial on “TPU support” and tried to finetune a tinyllama model. However I encountered an error after I run below code on Kaggle's TPU VM v3-8.

Could you please help me solve the error?
Thank you!

!pip install transformers datasets sentencepiece peft -q
!pip install torch --index-url https://download.pytorch.org/whl/cpu -q # Updating torch since we need the latest version
!pip install torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html -q
!pip uninstall tensorflow -y # If we don't do this, TF will take over TPU and cause permission error for PT
!pip install lightning@git+https://github.com/Lightning-AI/lightning@6dfa5cca9de5c28548eef5582a53c483b0eda66a
!pip install jsonargparse[signatures]
!apt update && apt install libopenblas-dev -y
!git clone https://github.com/Lightning-AI/lit-gpt.git
!export ALLOW_MULTIPLE_LIBTPU_LOAD=1
!export PJRT_DEVICE=TPU
%cd /kaggle/working/lit-gpt

!python scripts/download.py --repo_id TinyLlama/TinyLlama-1.1B-Chat-v0.6 --from_safetensors=True
!python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-Chat-v0.6
!python scripts/prepare_alpaca.py --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-Chat-v0.6
!python xla/finetune/adapter.py --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-Chat-v0.6 --precision bf16-true

[rank: 0] {'eval_interval': 200, 'save_interval': 200, 'eval_iters': 100, 'eval_max_new_tokens': 100, 'log_interval': 1, 'devices': 8, 'reduce_cpu_memory_usage_during_load': False, 'learning_rate': 0.003, 'batch_size': 8, 'micro_batch_size': 1, 'gradient_accumulation_iters': 8, 'epoch_size': 5000, 'num_epochs': 5, 'max_iters': 3125, 'weight_decay': 0.02, 'warmup_steps': 156}
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 56, in _run_thread_per_device
    initializer_fn(local_rank, local_world_size)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 115, in initialize_multiprocess
    devices = xm.get_xla_supported_devices()
  File "/usr/local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 91, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/usr/local/lib/python3.10/site-packages/torch_xla/utils/utils.py", line 29, in value
    self._value = self._gen_fn()
  File "/usr/local/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 19, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: Bad StatusOr access: UNKNOWN: TPU initialization failed: Invalid --2a886c8_slice_builder_worker_addresses specified. Expected 4 worker addresses, got 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/kaggle/working/lit-gpt/xla/finetune/adapter.py", line 284, in <module>
    CLI(setup)
  File "/usr/local/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/usr/local/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/kaggle/working/lit-gpt/xla/finetune/adapter.py", line 73, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/usr/local/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 839, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 924, in _wrap_and_launch
    return launcher.launch(to_run, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/lightning/fabric/strategies/launchers/xla.py", line 82, in launch
    xmp.spawn(
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 202, in spawn
    run_multiprocess(spawn_fn, start_method=start_method)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 159, in run_multiprocess
    replica_results = list(
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 160, in <genexpr>
    itertools.chain.from_iterable(
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: Bad StatusOr access: UNKNOWN: TPU initialization failed: Invalid --2a886c8_slice_builder_worker_addresses specified. Expected 4 worker addresses, got 1.

**Comment by IvoryTower800** [comment]
when I run below code
from torch_xla.experimental import tpu
tpu.get_tpu_env()

it returns

{'ACCELERATOR_TYPE': 'v3-8',
 'TPU_PROCESS_BOUNDS': '1,1,1',
 'TPU_CHIPS_PER_PROCESS_BOUNDS': '2,2,1',
 'WORKER_ID': '0'}

**Comment by carmocca** [comment]
cc @gkroiz since you referenced this key in https://github.com/Lightning-AI/lit-gpt/pull/186

Is `TYPE` not expected to exist always? Should it fallback to `env["ACCELERATOR_TYPE"].split("-")[0]`?

**Comment by gkroiz** [comment]
> cc @gkroiz since you referenced this key in #186
> 
> Is `TYPE` not expected to exist always? Should it fallback to `env["ACCELERATOR_TYPE"].split("-")[0]`?

I guess `TYPE` is not key for all TPU generations. Yes, we should fallback to `env["ACCELERATOR_TYPE"].split("-")[0]` for the older TPU generations.
