### ISSUE TITLE
RuntimeError: The size of tensor a (266) must match the size of tensor b (263) at non-singleton dimension 2

### ISSUE THREAD

**Issue by sendRainAutumn** [Lightning-AI/lit-gpt#939]
Hello, I used the code to finetune llama2-7b, vicuna-7b and falcon-7b. But I encountered the following bug.

```
Traceback (most recent call last):
  File "finetune/adapter.py", line 305, in <module>
    CLI(setup)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "finetune/adapter.py", line 93, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/lightning-2.2.0.dev0-py3.8.egg/lightning/fabric/fabric.py", line 861, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/lightning-2.2.0.dev0-py3.8.egg/lightning/fabric/fabric.py", line 947, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/lightning-2.2.0.dev0-py3.8.egg/lightning/fabric/fabric.py", line 952, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "finetune/adapter.py", line 135, in main
    train(fabric, model, optimizer, scheduler, train_data, val_data, checkpoint_dir, out_dir)
  File "finetune/adapter.py", line 204, in train
    val_loss = validate(fabric, model, val_data, tokenizer, max_iters=eval_iters)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "finetune/adapter.py", line 221, in validate
    logits = model(input_ids)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/lightning-2.2.0.dev0-py3.8.egg/lightning/fabric/wrappers.py", line 139, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lit-gpt/lit_gpt/adapter.py", line 70, in forward
    x = block(x, cos, sin, mask, input_pos)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lit-gpt/lit_gpt/model.py", line 155, in forward
    h = self.attn(n_1, cos, sin, mask, input_pos)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/lit-gpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lit-gpt/lit_gpt/model.py", line 215, in forward
    q_roped = apply_rope(q[..., : self.config.rope_n_elem], cos, sin)
  File "/home/lit-gpt/lit_gpt/model.py", line 346, in apply_rope
    roped = (x * cos) + (rotated * sin)
RuntimeError: The size of tensor a (266) must match the size of tensor b (263) at non-singleton dimension 2
```

My dataset is randomly sampled from a full data set. Sometimes the randomly sampled dataset can be finetuned normally. However, sometimes I encounter the above bug. I would like to ask why and how to solve it?

Below is information about my code environment:

- Python 3.8.18
- torch 2.1.1
- CUDA Version: 12.0 
- NVIDIA A100-PCIE-40GB

**Comment by sendRainAutumn** [comment]
> What does `model.max_seq_length` return? I suspect that you have samples in your data that are longer than this.
> 
> You should be seeing this here: https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/adapter.py#L159-L164

 `model.max_seq_length` is 768. Each data sample consists of three parts: Instruction, query, and context. The context length is truncated to 200, the query is an entity, the length does not exceed 10, and the Instruction length does not exceed 200.

**Comment by carmocca** [comment]
Notice that the error appears during validation. Did you check the validation data?

**Comment by sendRainAutumn** [comment]
> Notice that the error appears during validation. Did you check the validation data?

The data of Train and validate are processed in the same way. Instruction is exactly the same.

**Comment by Sreyan88** [comment]
I face the same problem!

**Comment by Sreyan88** [comment]
```
roped = (x * cos) + (rotated * sin) 
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 3 
```

**Comment by Borda** [comment]
Closing due to missing sample code or steps to reproduce...
Please, feel free to re-open with more details 🦩 
> A simple guide on how to create such a studio can be found [here](https://www.youtube.com/watch?v=YcW-2Zt_bFg&ab_channel=LightningAI).
