### ISSUE TITLE
Merge LoRA Weights Issue

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#960]
Hm, our `merge_lora.py` script may be broken or I am using it wrong. Here's an example to reproduce:

his section contains a reproducible example for finetuning a Lit-GPT model and converting it back into a HF `transformer` model.

1) Download a model of interest:

```bash
python scripts/download.py \
    --repo_id TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
```

2. Convert the model into the Lit-GPT format:

```bash
python scripts/convert_hf_checkpoint.py \
    --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
```

3. Prepare a dataset for finetuning:

```
python scripts/prepare_alpaca.py \
    --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T \
    --destination_path data/alpaca
```

4. Finetune the model using LoRA (we use a small epoch size for demonstration purposes):

```
python finetune/lora.py \
   --io.checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T/ \
   --io.train_data_dir data/alpaca \
   --io.val_data_dir data/alpaca \
   --train.epoch_size 50 \
   --train.epochs 1 \
   --io.out_dir out/lit-tinyllama
```

5. Merge weights

```
python scripts/merge_lora.py \
    --checkpoint_dir checkpoints/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T/ \
    --lora_path out/lit-tinyllama/lit_model_finetuned.pth \
    --out_dir out/lit-tinyllama/merged.pth
```

```
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/lit-gpt/scripts/merge_lora.py", line 83, in <module>
    CLI(merge_lora)
  File "/teamspace/studios/this_studio/lit-gpt/lit_gpt/utils.py", line 379, in CLI
    return CLI(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/jsonargparse/_cli.py", line 193, in _run_component
    return component(**cfg)
  File "/teamspace/studios/this_studio/lit-gpt/scripts/merge_lora.py", line 71, in merge_lora
    model.load_state_dict(checkpoint)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GPT:
        Missing key(s) in state_dict: "transformer.h.0.attn.attn.lora_A", "transformer.h.0.attn.attn.lora_B", "transformer.h.1.attn.attn.lora_A", "transformer.h.1.attn.attn.lora_B", "transformer.h.2.attn.attn.lora_A", "transformer.h.2.attn.attn.lora_B", "transformer.h.3.attn.attn.lora_A", "transformer.h.3.attn.attn.lora_B", "transformer.h.4.attn.attn.lora_A", "transformer.h.4.attn.attn.lora_B", "transformer.h.5.attn.attn.lora_A", "transformer.h.5.attn.attn.lora_B", "transformer.h.6.attn.attn.lora_A", "transformer.h.6.attn.attn.lora_B", "transformer.h.7.attn.attn.lora_A", "transformer.h.7.attn.attn.lora_B", "transformer.h.8.attn.attn.lora_A", "transformer.h.8.attn.attn.lora_B", "transformer.h.9.attn.attn.lora_A", "transformer.h.9.attn.attn.lora_B", "transformer.h.10.attn.attn.lora_A", "transformer.h.10.attn.attn.lora_B", "transformer.h.11.attn.attn.lora_A", "transformer.h.11.attn.attn.lora_B", "transformer.h.12.attn.attn.lora_A", "transformer.h.12.attn.attn.lora_B", "transformer.h.13.attn.attn.lora_A", "transformer.h.13.attn.attn.lora_B", "transformer.h.14.attn.attn.lora_A", "transformer.h.14.attn.attn.lora_B", "transformer.h.15.attn.attn.lora_A", "transformer.h.15.attn.attn.lora_B", "transformer.h.16.attn.attn.lora_A", "transformer.h.16.attn.attn.lora_B", "transformer.h.17.attn.attn.lora_A", "transformer.h.17.attn.attn.lora_B", "transformer.h.18.attn.attn.lora_A", "transformer.h.18.attn.attn.lora_B", "transformer.h.19.attn.attn.lora_A", "transformer.h.19.attn.attn.lora_B", "transformer.h.20.attn.attn.lora_A", "transformer.h.20.attn.attn.lora_B", "transformer.h.21.attn.attn.lora_A", "transformer.h.21.attn.attn.lora_B". 
```

**Comment by carmocca** [comment]
Looks like the LoRA path is empty. Can you share what `torch.load("out/lit-tinyllama/lit_model_finetuned.pth")` returns?

**Comment by Andrei-Aksionov** [comment]
Just tried it and couldn't repeat.
I had to make one change in step 5 (added \_lora\_):
```bash
--lora_path out/lit-tinyllama/lit_model_lora_finetuned.pth \
```

How likely that there is another model is saved in that folder? 🙂

**Comment by rasbt** [comment]
Could be that I messed up, sry! Let me take your shell variable approach from the other PR and then try this again. Pls don't waste time on it in the mean time, it could just be a me problem :)

**Comment by Andrei-Aksionov** [comment]
Or you can put all these commands in a single bash script and run only it.
Otherwise, during copy-paste you can accidentally make a mistake.

**Comment by rasbt** [comment]
Ah this was my bad @Andrei-Aksionov . Sorry about that and thanks for the pointer. I forgot the `*_lora_*`  and I accidentally also had a `lit_model_finetuned.pth` because I ran `full.py` before that, so that file existed.

**Comment by Magniveo** [comment]
The same problem occurs, working only with `model.load_state_dict(pretrained_checkpoint, strict=False)`
